<center><p float="center">
  <img src="https://upload.wikimedia.org/wikipedia/commons/e/e9/4_RGB_McCombs_School_Brand_Branded.png" width="300" height="100"/>
  <img src="https://mma.prnewswire.com/media/1458111/Great_Learning_Logo.jpg?p=facebook" width="200" height="100"/>
</p></center>

<center><font size=10>Artificial Intelligence and Machine Learning</center></font>
<center><font size=6>LLMs and Prompt Engineering</center></font>

<center><p float="center">
  <img src="https://images.pexels.com/photos/262918/pexels-photo-262918.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" width=720/>
</p></center>

<center><font size=6>Restaurant Review Analysis</center></font>

## Problem Statement

### Business Context

In the food industry, customer satisfaction plays a pivotal role in shaping the success of individual outlets and the overall brand. A leading global food aggregator is keen on understanding and improving customer experiences across the diverse range of restaurants it lists on its platform. The company recognizes the significance of customer reviews in gaining insights into service quality, food offerings, and overall satisfaction.

### Problem Definition

Despite the abundance of customer reviews available, the company faces significant challenges in deriving actionable insights from these valuable data sources. The manual analysis of extensive amounts of unstructured text data tends to be time-consuming and non-scalable. The key problems to address include:

- **Unstructured Data Challenge**: Customer reviews are expressed in natural language and an unstructured format, creating difficulties in efficiently extracting meaningful information.

- **Scale of Data**: With numerous restaurants, the company accumulates a substantial volume of reviews. Manually processing this vast amount of data is not scalable and necessitates an automated approach.

- **Customer Sentiment Understanding**: Discerning customer sentiments from reviews, whether positive, negative, or neutral, poses a significant challenge. This understanding is crucial for the company to identify the preferences of different customers and devise strategies for targeted marketing.

### Objective

As a data scientist at the company, you have been provided a sample of the customer review data and asked to created a predictive model to analyze the reviews. The objective is to build a robust sentiment analyzer using a Large Language Model (LLM) that accurately predicts the sentiment of customers from the reviews, thereby enhancing the company's ability to understand customer sentiments at scale, enabling data-driven decision-making, and improving overall customer satisfaction.

## Installing and Importing Necessary Libraries

In [ ]:
# Installation for GPU llama-cpp-python
# uncomment and run the following code in case GPU is being used
!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.2.45 --force-reinstall --no-cache-dir -q

# Installation for CPU llama-cpp-python
# uncomment and run the following code in case GPU is not being used
# !CMAKE_ARGS="-DLLAMA_CUBLAS=off" FORCE_CMAKE=1 pip install llama-cpp-python==0.2.45 --force-reinstall --no-cache-dir -q

**Note**:
- After running the above cell, kindly restart the runtime (for Google Colab) or notebook kernel (for Jupyter Notebook), and run all cells sequentially from the next cell.
- On executing the above line of code, you might see a warning regarding package dependencies. This error message can be ignored as the above code ensures that all necessary libraries and their dependencies are maintained to successfully execute the code in ***this notebook***.

In [ ]:
# For downloading the models from HF Hub
!pip install huggingface_hub==0.20.3 pandas==2.2.2 -q

**Note**:
- After running the above cell, kindly restart the runtime (for Google Colab) or notebook kernel (for Jupyter Notebook), and run all cells sequentially from the next cell.
- On executing the above line of code, you might see a warning regarding package dependencies. This error message can be ignored as the above code ensures that all necessary libraries and their dependencies are maintained to successfully execute the code in ***this notebook***.

In [ ]:
# Importing library for data manipulation
import pandas as pd

# Function to download the model from the Hugging Face model hub
from huggingface_hub import hf_hub_download

# Importing the Llama class from the llama_cpp module
from llama_cpp import Llama

# Importing the json module
import json

## Import the dataset

In [ ]:
# uncomment and run the below code snippets if the dataset is present in the Google Drive
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
data = pd.read_csv("restaurant_reviews.csv")

## Data Overview

In [ ]:
# checking the first five rows of the data
data.head()

,restaurant_ID,rating_review,review_full
0,FLV202,5,"Totally in love with the Auro of the place, re..."
1,SAV303,5,Kailash colony is brimming with small cafes no...
2,YUM789,5,Excellent taste and awesome decorum. Must visi...
3,TST101,5,I have visited at jw lough/restourant. There w...
4,EAT456,5,Had a great experience in the restaurant food ...

In [ ]:
# checking the shape of the data
data.shape

(20, 3)

**Observations**

- Data has 20 rows and 3 columns

In [ ]:
# checking for missing values
data.isnull().sum()

restaurant_ID    0
rating_review    0
review_full      0
dtype: int64

**Observations**

- There are no missing values in the data

In [ ]:
max_len_review = data.loc[data['review_full'].str.len().idxmax(), 'review_full']
print("The longest review_full is:")
print(max_len_review)

The longest review_full is:
I went to Pluck (Hotel Pullman) on a Friday night. We were a group of 7 adults and 1 infant. There weren’t many people in the restaurant when we reached around 10:20PM and very soon the ones that were there also left. So eventually it was just all of us on one table and after that no one else came. Some person came to our table and introduced himself as Ashish and told us that he would take care of our table. The menus were in a tablet which seemed impressive. We were coming straight from the airport after our journey and were hungry and tired too. We quickly ordered 3 set menus, some food items and some drinks. The service from the very beginning was very slow. Apart from Ashish, we could see about 4-5 more waiters inside the restaurant; but when it came to servicing our table, it was only Ashish who was doing it and couldn’t do it effectively. We kept waiting for our order; we had to call him so many times to remind him to bring our order, particularly the next dish of our set menu. Looked like the chef also couldn’t manage. The tomato and coriander consommé (more commonly known as tomato dhaniya shorba in India) was a big disappointment! There were few pieces of tomato and coriander (or some greens) and he gave some sort of liquid to pour over it which was bland, watery and didn’t give the soup any taste. The organic quinoa broccoli cake that I got was burnt/over cooked and I left it. The pan roasted lamb Loin that was ordered for the second time was undercooked. Some of the food items that we got were decent in taste but the service level was so poor that the overall experience was very disappointing. We were in the restaurant for almost 2 hours, only waiting for our food to come, with only one person looking after the needs of 8 people! And in the end came the bill which was a bomb (Price for one person came out to approx INR3,000). It seemed an absurd figure, considering the extremely poor service that we received on a Friday night at a Fine Dining restaurant of a renowned hotel near the airport. I would not recommend this place to a family, especially if you are coming back from or going to the airport; you might just end up with a long wait!

# Model Building

### Loading the model (Llama)

In [ ]:
model_name_or_path = "TheBloke/Llama-2-13B-chat-GGUF"
model_basename = "llama-2-13b-chat.Q5_K_M.gguf" # the model is in gguf format

In [ ]:
# Using hf_hub_download to download a model from the Hugging Face model hub
# The repo_id parameter specifies the model name or path in the Hugging Face repository
# The filename parameter specifies the name of the file to download
model_path = hf_hub_download(
    repo_id=model_name_or_path,
    filename=model_basename
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
lcpp_llm = Llama(
    model_path=model_path,
    n_threads=2,  # CPU cores
    n_batch=256,  # Should be between 1 and n_ctx, consider the amount of VRAM in your GPU.
    # n_gpu_layers=41,  # determines the number of GPU layers to utilize; uncomment this line if GPU is available
    n_ctx=1440,  # Context window
)

llama_model_loader: loaded meta data with 19 key-value pairs and 363 tensors from /root/.cache/huggingface/hub/models--TheBloke--Llama-2-13B-chat-GGUF/snapshots/4458acc949de0a9914c3eab623904d4fe999050a/llama-2-13b-chat.Q5_K_M.gguf (version GGUF V2)
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 5120
llama_model_loader: - kv   4:                          llama.block_count u32              = 40
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 13824
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 40
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 40
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 17
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  17:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  18:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   81 tensors
llama_model_loader: - type q5_K:  241 tensors
llama_model_loader: - type q6_K:   41 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V2
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 5120
llm_load_print_meta: n_head           = 40
llm_load_print_meta: n_head_kv        = 40
llm_load_print_meta: n_layer          = 40
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 5120
llm_load_print_meta: n_embd_v_gqa     = 5120
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 13824
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 13B
llm_load_print_meta: model ftype      = Q5_K - Medium
llm_load_print_meta: model params     = 13.02 B
llm_load_print_meta: model size       = 8.60 GiB (5.67 BPW)
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.28 MiB
llm_load_tensors: offloading 40 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 41/41 layers to GPU
llm_load_tensors:        CPU buffer size =   107.42 MiB
llm_load_tensors:      CUDA0 buffer size =  8694.21 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 1440
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      CUDA0 KV buffer size =  1125.00 MiB
llama_new_context_with_model: KV self size  = 1125.00 MiB, K (f16):  562.50 MiB, V (f16):  562.50 MiB
llama_new_context_with_model:  CUDA_Host input buffer size   =     6.67 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =    77.66 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =     5.00 MiB
llama_new_context_with_model: graph splits (measure): 3
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 |
Model metadata: {'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'general.architecture': 'llama', 'llama.context_length': '4096', 'general.name': 'LLaMA v2', 'llama.embedding_length': '5120', 'llama.feed_forward_length': '13824', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'llama.rope.dimension_count': '128', 'llama.attention.head_count': '40', 'tokenizer.ggml.bos_token_id': '1', 'llama.block_count': '40', 'llama.attention.head_count_kv': '40', 'general.quantization_version': '2', 'tokenizer.ggml.model': 'llama', 'general.file_type': '17'}

### Loading the model (Mistral)

In [ ]:
model_name_or_path = "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
model_basename = "mistral-7b-instruct-v0.2.Q6_K.gguf"

In [ ]:
model_path = hf_hub_download(
    repo_id=model_name_or_path,
    filename=model_basename
)

In [ ]:
llm = Llama(
    model_path=model_path,
    n_threads=2,  # CPU cores
    n_batch=200,  # Should be between 1 and n_ctx, consider the amount of VRAM in your GPU.
    # n_gpu_layers=22,  # determines the number of GPU layers to utilize; uncomment this line if GPU is available
    n_ctx=900,
)

### Defining Model Response Parameters

In [ ]:
def generate_response(model_instance, prompt, params=None):
    # Set standard defaults including all requested parameters
    config = {
        "max_tokens": 1024,
        "temperature": 0.01,
        "top_p": 0.95,
        "repeat_penalty": 1.2,
        "top_k": 50,
        "stop": ["[/INST]", "Q:", "INST", "\n\n"],
        "echo": False,
        "seed": 42
    }

    # Update config if specific params are passed during the call
    if params:
        config.update(params)

    # Calling the model instance with the unpacked configuration
    response = model_instance(
        prompt=prompt,
        **config
    )

    return response["choices"][0]["text"].strip()

- **`max_tokens`**: This parameter **specifies the maximum number of tokens that the model should generate** in response to the prompt.

- **`temperature`**: This parameter **controls the randomness of the generated response**. A higher temperature value will result in a more random response, while a lower temperature value will result in a more predictable response.

- **`top_p`**: This parameter **controls the diversity of the generated response by establishing a cumulative probability cutoff for token selection**. A higher value of top_p will result in a more diverse response, while a lower value will result in a less diverse response.

- **`repeat_penalty`**: This parameter **controls the penalty for repeating tokens in the generated response**. A higher value of repeat_penalty will result in a lower probability of repeating tokens, while a lower value will result in a higher probability of repeating tokens.

- **`top_k`**: This parameter **controls the maximum number of most-likely next tokens to consider** when generating the response at each step.

- **`stop`**: This parameter is a **list of tokens that are used to dynamically stop response generation** whenever the tokens in the list are encountered.

- **`echo`**: This parameter **controls whether the input (prompt) to the model should be returned** in the model response.

- **`seed`**: This parameter **specifies a seed value that helps replicate results**.

### Utility function

In [ ]:
# defining a function to parse the JSON output from the model
def extract_json_data(json_str):
    try:
        # Find the indices of the opening and closing curly braces
        json_start = json_str.find('{')
        json_end = json_str.rfind('}')

        if json_start != -1 and json_end != -1:
            extracted_sentiment = json_str[json_start:json_end + 1]  # Extract the JSON object
            data_dict = json.loads(extracted_sentiment)
            return data_dict
        else:
            print(f"Warning: JSON object not found in response: {json_str}")
            return {}
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}")
        return {}

## 1. Sentiment Analysis (Llama)

In [ ]:
# creating a copy of the data
data_1 = data.copy()

In [ ]:
# defining the instructions for the model
instruction_1 = """
    You are an AI analyzing restaurant reviews. Classify the sentiment of the provided review into only one of the following categories:
    - Positive
    - Negative
    - Neutral
"""

In [ ]:
# 1. Define the parameters for this specific task
params_task_1 = {"max_tokens": 1024, "temperature": 0.01}

# 2. Apply the optimized generate_response function
data_1['model_response'] = data_1['review_full'].apply(
    lambda x: generate_response(
        lcpp_llm,
        f"[INST]<<SYS>>\n{instruction_1}\n<</SYS>>\n{x}[/INST]",
        params_task_1
    )
)

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      79.11 ms /   121 runs   (    0.65 ms per token,  1529.54 tokens per second)
llama_print_timings: prompt eval time =    1036.86 ms /   234 tokens (    4.43 ms per token,   225.68 tokens per second)
llama_print_timings:        eval time =    8211.98 ms /   120 runs   (   68.43 ms per token,    14.61 tokens per second)
llama_print_timings:       total time =    9875.30 ms /   354 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      54.71 ms /    91 runs   (    0.60 ms per token,  1663.41 tokens per second)
llama_print_timings: prompt eval time =     712.87 ms /   243 tokens (    2.93 ms per token,   340.88 tokens per second)
llama_print_timings:        eval time =    6725.56 ms /    90 runs   (   74.73 ms per token,    13.38 tokens per second)
llama_print_timings:       total time =    7829.65 ms /   333 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      40.78 ms /    70 runs   (    0.58 ms per token,  1716.61 tokens per second)
llama_print_timings: prompt eval time =     409.05 ms /    33 tokens (   12.40 ms per token,    80.67 tokens per second)
llama_print_timings:        eval time =    5282.19 ms /    69 runs   (   76.55 ms per token,    13.06 tokens per second)
llama_print_timings:       total time =    5976.62 ms /   102 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       9.63 ms /    17 runs   (    0.57 ms per token,  1765.50 tokens per second)
llama_print_timings: prompt eval time =     632.83 ms /   144 tokens (    4.39 ms per token,   227.55 tokens per second)
llama_print_timings:        eval time =    1238.78 ms /    16 runs   (   77.42 ms per token,    12.92 tokens per second)
llama_print_timings:       total time =    1937.17 ms /   160 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      58.03 ms /    93 runs   (    0.62 ms per token,  1602.51 tokens per second)
llama_print_timings: prompt eval time =     670.55 ms /   181 tokens (    3.70 ms per token,   269.93 tokens per second)
llama_print_timings:        eval time =    7034.81 ms /    92 runs   (   76.47 ms per token,    13.08 tokens per second)
llama_print_timings:       total time =    8140.83 ms /   273 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      86.53 ms /   144 runs   (    0.60 ms per token,  1664.26 tokens per second)
llama_print_timings: prompt eval time =     731.24 ms /   223 tokens (    3.28 ms per token,   304.96 tokens per second)
llama_print_timings:        eval time =   10938.33 ms /   143 runs   (   76.49 ms per token,    13.07 tokens per second)
llama_print_timings:       total time =   12313.14 ms /   366 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      71.09 ms /   116 runs   (    0.61 ms per token,  1631.83 tokens per second)
llama_print_timings: prompt eval time =     713.74 ms /   229 tokens (    3.12 ms per token,   320.85 tokens per second)
llama_print_timings:        eval time =    8575.87 ms /   115 runs   (   74.57 ms per token,    13.41 tokens per second)
llama_print_timings:       total time =    9820.91 ms /   344 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      43.85 ms /    79 runs   (    0.56 ms per token,  1801.76 tokens per second)
llama_print_timings: prompt eval time =     462.26 ms /    70 tokens (    6.60 ms per token,   151.43 tokens per second)
llama_print_timings:        eval time =    5592.34 ms /    78 runs   (   71.70 ms per token,    13.95 tokens per second)
llama_print_timings:       total time =    6362.56 ms /   148 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      54.16 ms /    90 runs   (    0.60 ms per token,  1661.71 tokens per second)
llama_print_timings: prompt eval time =     451.70 ms /    71 tokens (    6.36 ms per token,   157.18 tokens per second)
llama_print_timings:        eval time =    6248.86 ms /    89 runs   (   70.21 ms per token,    14.24 tokens per second)
llama_print_timings:       total time =    7103.56 ms /   160 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      46.83 ms /    88 runs   (    0.53 ms per token,  1879.18 tokens per second)
llama_print_timings: prompt eval time =     446.81 ms /    71 tokens (    6.29 ms per token,   158.90 tokens per second)
llama_print_timings:        eval time =    6189.26 ms /    87 runs   (   71.14 ms per token,    14.06 tokens per second)
llama_print_timings:       total time =    6926.62 ms /   158 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      39.18 ms /    63 runs   (    0.62 ms per token,  1608.09 tokens per second)
llama_print_timings: prompt eval time =     453.69 ms /    70 tokens (    6.48 ms per token,   154.29 tokens per second)
llama_print_timings:        eval time =    4331.59 ms /    62 runs   (   69.86 ms per token,    14.31 tokens per second)
llama_print_timings:       total time =    5079.91 ms /   132 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      55.53 ms /   106 runs   (    0.52 ms per token,  1908.74 tokens per second)
llama_print_timings: prompt eval time =     455.08 ms /    71 tokens (    6.41 ms per token,   156.02 tokens per second)
llama_print_timings:        eval time =    7612.20 ms /   105 runs   (   72.50 ms per token,    13.79 tokens per second)
llama_print_timings:       total time =    8420.88 ms /   176 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      47.74 ms /    76 runs   (    0.63 ms per token,  1591.86 tokens per second)
llama_print_timings: prompt eval time =     450.26 ms /    65 tokens (    6.93 ms per token,   144.36 tokens per second)
llama_print_timings:        eval time =    5455.61 ms /    75 runs   (   72.74 ms per token,    13.75 tokens per second)
llama_print_timings:       total time =    6234.90 ms /   140 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      64.24 ms /   112 runs   (    0.57 ms per token,  1743.35 tokens per second)
llama_print_timings: prompt eval time =    1218.40 ms /   371 tokens (    3.28 ms per token,   304.50 tokens per second)
llama_print_timings:        eval time =    8471.27 ms /   111 runs   (   76.32 ms per token,    13.10 tokens per second)
llama_print_timings:       total time =   10138.68 ms /   482 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      89.09 ms /   160 runs   (    0.56 ms per token,  1795.98 tokens per second)
llama_print_timings: prompt eval time =    2267.65 ms /   542 tokens (    4.18 ms per token,   239.01 tokens per second)
llama_print_timings:        eval time =   12210.57 ms /   159 runs   (   76.80 ms per token,    13.02 tokens per second)
llama_print_timings:       total time =   15134.82 ms /   701 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      98.06 ms /   174 runs   (    0.56 ms per token,  1774.46 tokens per second)
llama_print_timings: prompt eval time =    1438.34 ms /   283 tokens (    5.08 ms per token,   196.75 tokens per second)
llama_print_timings:        eval time =   13116.58 ms /   173 runs   (   75.82 ms per token,    13.19 tokens per second)
llama_print_timings:       total time =   15220.02 ms /   456 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      59.11 ms /   101 runs   (    0.59 ms per token,  1708.68 tokens per second)
llama_print_timings: prompt eval time =    1513.35 ms /   287 tokens (    5.27 ms per token,   189.65 tokens per second)
llama_print_timings:        eval time =    7469.00 ms /   100 runs   (   74.69 ms per token,    13.39 tokens per second)
llama_print_timings:       total time =    9388.33 ms /   387 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      63.74 ms /   113 runs   (    0.56 ms per token,  1772.88 tokens per second)
llama_print_timings: prompt eval time =    1178.56 ms /   351 tokens (    3.36 ms per token,   297.82 tokens per second)
llama_print_timings:        eval time =    8345.91 ms /   112 runs   (   74.52 ms per token,    13.42 tokens per second)
llama_print_timings:       total time =    9965.10 ms /   463 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      57.08 ms /   110 runs   (    0.52 ms per token,  1927.09 tokens per second)
llama_print_timings: prompt eval time =    1375.32 ms /   481 tokens (    2.86 ms per token,   349.74 tokens per second)
llama_print_timings:        eval time =    8342.80 ms /   109 runs   (   76.54 ms per token,    13.07 tokens per second)
llama_print_timings:       total time =   10088.57 ms /   590 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      47.54 ms /    86 runs   (    0.55 ms per token,  1808.85 tokens per second)
llama_print_timings: prompt eval time =    1089.37 ms /   304 tokens (    3.58 ms per token,   279.06 tokens per second)
llama_print_timings:        eval time =    6281.64 ms /    85 runs   (   73.90 ms per token,    13.53 tokens per second)
llama_print_timings:       total time =    7702.35 ms /   389 tokens

In [ ]:
data_1['model_response'].head()

0    The sentiment of the review is Positive. The r...
1    Sure! Based on the review, I would classify th...
2    Sure! Based on the review you provided, I woul...
3    Sure! Here's my analysis of the sentiment in y...
4    Sure! Based on the review, I would classify th...
Name: model_response, dtype: object

In [ ]:
i = 2
print(data_1.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [ ]:
print(data_1.loc[i, 'model_response'])

Sure! Based on the review you provided, I would classify the sentiment as Positive. The reviewer mentions "excellent taste" and "awesome decorum," which suggests that they had a positive experience at the restaurant. Additionally, they mention "one of the best experiences," which further reinforces a positive sentiment.

In [ ]:
def extract_sentiment(model_response):
    if 'positive' in model_response.lower():
        return 'Positive'
    elif 'negative' in model_response.lower():
        return 'Negative'
    elif 'neutral' in model_response.lower():
        return 'Neutral'

In [ ]:
# applying the function to the model response
data_1['sentiment'] = data_1['model_response'].apply(extract_sentiment)
data_1['sentiment'].head()

0    Positive
1    Positive
2    Positive
3        None
4    Positive
Name: sentiment, dtype: object

In [ ]:
data_1['sentiment'].value_counts()

sentiment
Positive    16
Negative     2
Neutral      1
Name: count, dtype: int64

In [ ]:
final_data_1 = data_1.drop(['model_response'], axis=1)
final_data_1.head()

,restaurant_ID,rating_review,review_full,sentiment
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,None
4,EAT456,5,Had a great experience in the restaurant food ...,Positive

**Observations**

- The model provides long conversational explanations instead of just the requested label i.e., Postitive/Negative/Neutral.

- It repeats phrases from the review to justify its sentiment classification.

- The output format is inconsistent and difficult to parse for automated systems and pass through APIs.

## 1. Sentiment Analysis (Mistral)

In [ ]:
# creating a copy of the data
data_1 = data.copy()

**We are going to use an instruction-tuned Mistral model. Hence, the format of the input to the model varies from that of Llama.**

In [ ]:
# defining the instructions for the model
instruction_1 = """
    You are an AI analyzing restaurant reviews. Classify the sentiment of the provided review into only one of the following categories:
    - Positive
    - Negative
    - Neutral
"""

In [ ]:
# 1. Define the parameters for Task 1 (Mistral)
params_mistral_1 = {"max_tokens": 600, "temperature": 0.01}

# 2. Apply the optimized function using the merged f-string
data_1['model_response'] = data_1['review_full'].apply(
    lambda x: generate_response(
        llm,
        f"Q: {instruction_1}\nReview: {x}\nA:",
        params_mistral_1
    )
)

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      88.05 ms /   151 runs   (    0.58 ms per token,  1715.03 tokens per second)
llama_print_timings: prompt eval time =    5307.50 ms /   214 tokens (   24.80 ms per token,    40.32 tokens per second)
llama_print_timings:        eval time =   45595.21 ms /   150 runs   (  303.97 ms per token,     3.29 tokens per second)
llama_print_timings:       total time =   51579.16 ms /   364 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      40.85 ms /    67 runs   (    0.61 ms per token,  1639.99 tokens per second)
llama_print_timings: prompt eval time =    1873.51 ms /   232 tokens (    8.08 ms per token,   123.83 tokens per second)
llama_print_timings:        eval time =   20912.76 ms /    66 runs   (  316.86 ms per token,     3.16 tokens per second)
llama_print_timings:       total time =   23074.65 ms /   298 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      26.49 ms /    45 runs   (    0.59 ms per token,  1698.82 tokens per second)
llama_print_timings: prompt eval time =    5857.53 ms /    31 tokens (  188.95 ms per token,     5.29 tokens per second)
llama_print_timings:        eval time =   13405.51 ms /    44 runs   (  304.67 ms per token,     3.28 tokens per second)
llama_print_timings:       total time =   19455.39 ms /    75 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       1.66 ms /     3 runs   (    0.55 ms per token,  1809.41 tokens per second)
llama_print_timings: prompt eval time =     863.06 ms /   140 tokens (    6.16 ms per token,   162.21 tokens per second)
llama_print_timings:        eval time =     457.59 ms /     2 runs   (  228.80 ms per token,     4.37 tokens per second)
llama_print_timings:       total time =    1331.84 ms /   142 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      45.10 ms /    78 runs   (    0.58 ms per token,  1729.37 tokens per second)
llama_print_timings: prompt eval time =     884.62 ms /   166 tokens (    5.33 ms per token,   187.65 tokens per second)
llama_print_timings:        eval time =   23313.95 ms /    77 runs   (  302.78 ms per token,     3.30 tokens per second)
llama_print_timings:       total time =   24522.27 ms /   243 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      27.15 ms /    48 runs   (    0.57 ms per token,  1768.15 tokens per second)
llama_print_timings: prompt eval time =    3533.61 ms /   214 tokens (   16.51 ms per token,    60.56 tokens per second)
llama_print_timings:        eval time =   13443.70 ms /    47 runs   (  286.04 ms per token,     3.50 tokens per second)
llama_print_timings:       total time =   17174.74 ms /   261 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      57.87 ms /    98 runs   (    0.59 ms per token,  1693.57 tokens per second)
llama_print_timings: prompt eval time =    3921.38 ms /   212 tokens (   18.50 ms per token,    54.06 tokens per second)
llama_print_timings:        eval time =   28064.73 ms /    97 runs   (  289.33 ms per token,     3.46 tokens per second)
llama_print_timings:       total time =   32390.38 ms /   309 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       2.26 ms /     4 runs   (    0.57 ms per token,  1766.78 tokens per second)
llama_print_timings: prompt eval time =     740.07 ms /    66 tokens (   11.21 ms per token,    89.18 tokens per second)
llama_print_timings:        eval time =     704.64 ms /     3 runs   (  234.88 ms per token,     4.26 tokens per second)
llama_print_timings:       total time =    1458.56 ms /    69 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       2.18 ms /     4 runs   (    0.54 ms per token,  1836.55 tokens per second)
llama_print_timings: prompt eval time =     682.67 ms /    64 tokens (   10.67 ms per token,    93.75 tokens per second)
llama_print_timings:        eval time =     697.15 ms /     3 runs   (  232.38 ms per token,     4.30 tokens per second)
llama_print_timings:       total time =    1394.43 ms /    67 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       2.15 ms /     4 runs   (    0.54 ms per token,  1860.47 tokens per second)
llama_print_timings: prompt eval time =     680.04 ms /    65 tokens (   10.46 ms per token,    95.58 tokens per second)
llama_print_timings:        eval time =     667.86 ms /     3 runs   (  222.62 ms per token,     4.49 tokens per second)
llama_print_timings:       total time =    1363.16 ms /    68 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       2.25 ms /     4 runs   (    0.56 ms per token,  1779.36 tokens per second)
llama_print_timings: prompt eval time =     689.01 ms /    62 tokens (   11.11 ms per token,    89.98 tokens per second)
llama_print_timings:        eval time =     697.70 ms /     3 runs   (  232.57 ms per token,     4.30 tokens per second)
llama_print_timings:       total time =    1401.79 ms /    65 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       2.14 ms /     4 runs   (    0.54 ms per token,  1867.41 tokens per second)
llama_print_timings: prompt eval time =     696.60 ms /    68 tokens (   10.24 ms per token,    97.62 tokens per second)
llama_print_timings:        eval time =     704.63 ms /     3 runs   (  234.88 ms per token,     4.26 tokens per second)
llama_print_timings:       total time =    1415.26 ms /    71 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       2.54 ms /     4 runs   (    0.63 ms per token,  1577.91 tokens per second)
llama_print_timings: prompt eval time =     727.71 ms /    61 tokens (   11.93 ms per token,    83.82 tokens per second)
llama_print_timings:        eval time =    2261.36 ms /     3 runs   (  753.79 ms per token,     1.33 tokens per second)
llama_print_timings:       total time =    3012.32 ms /    64 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       1.68 ms /     3 runs   (    0.56 ms per token,  1782.53 tokens per second)
llama_print_timings: prompt eval time =    1986.12 ms /   351 tokens (    5.66 ms per token,   176.73 tokens per second)
llama_print_timings:        eval time =     475.09 ms /     2 runs   (  237.55 ms per token,     4.21 tokens per second)
llama_print_timings:       total time =    2476.27 ms /   353 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       1.61 ms /     3 runs   (    0.54 ms per token,  1858.74 tokens per second)
llama_print_timings: prompt eval time =    2843.03 ms /   523 tokens (    5.44 ms per token,   183.96 tokens per second)
llama_print_timings:        eval time =     454.76 ms /     2 runs   (  227.38 ms per token,     4.40 tokens per second)
llama_print_timings:       total time =    3315.11 ms /   525 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       1.71 ms /     3 runs   (    0.57 ms per token,  1759.53 tokens per second)
llama_print_timings: prompt eval time =    1690.09 ms /   271 tokens (    6.24 ms per token,   160.35 tokens per second)
llama_print_timings:        eval time =     462.44 ms /     2 runs   (  231.22 ms per token,     4.32 tokens per second)
llama_print_timings:       total time =    2167.96 ms /   273 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       1.65 ms /     3 runs   (    0.55 ms per token,  1820.39 tokens per second)
llama_print_timings: prompt eval time =    1705.91 ms /   281 tokens (    6.07 ms per token,   164.72 tokens per second)
llama_print_timings:        eval time =     486.19 ms /     2 runs   (  243.09 ms per token,     4.11 tokens per second)
llama_print_timings:       total time =    2206.42 ms /   283 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       1.91 ms /     3 runs   (    0.64 ms per token,  1573.98 tokens per second)
llama_print_timings: prompt eval time =    2057.65 ms /   332 tokens (    6.20 ms per token,   161.35 tokens per second)
llama_print_timings:        eval time =     777.32 ms /     2 runs   (  388.66 ms per token,     2.57 tokens per second)
llama_print_timings:       total time =    2855.41 ms /   334 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       1.58 ms /     3 runs   (    0.53 ms per token,  1896.33 tokens per second)
llama_print_timings: prompt eval time =    2698.62 ms /   459 tokens (    5.88 ms per token,   170.09 tokens per second)
llama_print_timings:        eval time =     456.66 ms /     2 runs   (  228.33 ms per token,     4.38 tokens per second)
llama_print_timings:       total time =    3174.14 ms /   461 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =       1.55 ms /     3 runs   (    0.52 ms per token,  1929.26 tokens per second)
llama_print_timings: prompt eval time =    1703.97 ms /   294 tokens (    5.80 ms per token,   172.54 tokens per second)
llama_print_timings:        eval time =     448.93 ms /     2 runs   (  224.47 ms per token,     4.46 tokens per second)
llama_print_timings:       total time =    2166.33 ms /   296 tokens

In [ ]:
data_1['model_response'].head()

0    This review expresses a very positive sentimen...
1    The sentiment expressed in this review is posi...
2    The given review expresses a positive sentimen...
3                                             Positive
4    This review expresses a positive sentiment tow...
Name: model_response, dtype: object

In [ ]:
i = 2
print(data_1.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [ ]:
print(data_1.loc[i, 'model_response'])

The given review expresses a positive sentiment towards the restaurant, as indicated by words such as "excellent," "awesome," "must visit," "great service," and "one of the best experience."

In [ ]:
def extract_sentiment(model_response):
    if 'positive' in model_response.lower():
        return 'Positive'
    elif 'negative' in model_response.lower():
        return 'Negative'
    elif 'neutral' in model_response.lower():
        return 'Neutral'

In [ ]:
# applying the function to the model response
data_1['sentiment'] = data_1['model_response'].apply(extract_sentiment)
data_1['sentiment'].head()

0    Positive
1    Positive
2    Positive
3    Positive
4    Positive
Name: sentiment, dtype: object

In [ ]:
data_1['sentiment'].value_counts()

sentiment
Positive    7
Negative    7
Neutral     6
Name: count, dtype: int64

In [ ]:
final_data_1 = data_1.drop(['model_response'], axis=1)
final_data_1.head()

,restaurant_ID,rating_review,review_full,sentiment
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,Positive
4,EAT456,5,Had a great experience in the restaurant food ...,Positive

**Observations**

- The model includes a summary of the review's tone before providing the sentiment.

- The output format is inconsistent and difficult to parse for automated systems and pass through APIs.

## 2. Sentiment Analysis and Returning Structured Output (Llama)

In [ ]:
# creating a copy of the data
data_2 = data.copy()

In [ ]:
# defining the instructions for the model
instruction_2 = """
    You are an AI analyzing restaurant reviews. Classify the sentiment of the provided review into the following categories:
    - Positive
    - Negative
    - Neutral

    Format the output as a JSON object with a single key-value pair as shown below:
    {"sentiment": "your_sentiment_prediction"}

    Only return the JSON, do not return any other information.
"""

In [ ]:
# 1. (Optional) Define a parameter override to save compute time
params_task_2 = {"max_tokens": 128}

# 2. Apply the optimized function
# We add '{"' at the end of the prompt to force the JSON structure
data_2['model_response'] = data_2['review_full'].apply(
    lambda x: "{" + generate_response(
        lcpp_llm,
        f"[INST]<<SYS>>\n{instruction_2}\n<</SYS>>\n{x}[/INST]\n{{",
        params_task_2
    )
)

Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.33 ms /    10 runs   (    0.53 ms per token,  1876.88 tokens per second)
llama_print_timings: prompt eval time =     680.73 ms /   254 tokens (    2.68 ms per token,   373.13 tokens per second)
llama_print_timings:        eval time =     674.73 ms /     9 runs   (   74.97 ms per token,    13.34 tokens per second)
llama_print_timings:       total time =    1390.11 ms /   263 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.32 ms /    10 runs   (    0.53 ms per token,  1878.29 tokens per second)
llama_print_timings: prompt eval time =     692.12 ms /   245 tokens (    2.82 ms per token,   353.98 tokens per second)
llama_print_timings:        eval time =     683.50 ms /     9 runs   (   75.94 ms per token,    13.17 tokens per second)
llama_print_timings:       total time =    1408.38 ms /   254 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.27 ms /    10 runs   (    0.53 ms per token,  1898.61 tokens per second)
llama_print_timings: prompt eval time =     410.56 ms /    35 tokens (   11.73 ms per token,    85.25 tokens per second)
llama_print_timings:        eval time =     678.00 ms /     9 runs   (   75.33 ms per token,    13.27 tokens per second)
llama_print_timings:       total time =    1122.09 ms /    44 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       7.26 ms /    10 runs   (    0.73 ms per token,  1376.65 tokens per second)
llama_print_timings: prompt eval time =     608.18 ms /   146 tokens (    4.17 ms per token,   240.06 tokens per second)
llama_print_timings:        eval time =     670.64 ms /     9 runs   (   74.52 ms per token,    13.42 tokens per second)
llama_print_timings:       total time =    1330.89 ms /   155 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       7.08 ms /    10 runs   (    0.71 ms per token,  1411.63 tokens per second)
llama_print_timings: prompt eval time =     653.48 ms /   183 tokens (    3.57 ms per token,   280.04 tokens per second)
llama_print_timings:        eval time =     659.03 ms /     9 runs   (   73.23 ms per token,    13.66 tokens per second)
llama_print_timings:       total time =    1369.49 ms /   192 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.20 ms /    10 runs   (    0.52 ms per token,  1922.71 tokens per second)
llama_print_timings: prompt eval time =     668.18 ms /   225 tokens (    2.97 ms per token,   336.73 tokens per second)
llama_print_timings:        eval time =     698.55 ms /     9 runs   (   77.62 ms per token,    12.88 tokens per second)
llama_print_timings:       total time =    1399.32 ms /   234 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       6.00 ms /    11 runs   (    0.55 ms per token,  1833.03 tokens per second)
llama_print_timings: prompt eval time =     682.67 ms /   231 tokens (    2.96 ms per token,   338.38 tokens per second)
llama_print_timings:        eval time =     769.87 ms /    10 runs   (   76.99 ms per token,    12.99 tokens per second)
llama_print_timings:       total time =    1489.03 ms /   241 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.20 ms /    10 runs   (    0.52 ms per token,  1923.82 tokens per second)
llama_print_timings: prompt eval time =     473.83 ms /    72 tokens (    6.58 ms per token,   151.95 tokens per second)
llama_print_timings:        eval time =     669.46 ms /     9 runs   (   74.38 ms per token,    13.44 tokens per second)
llama_print_timings:       total time =    1175.42 ms /    81 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.28 ms /    10 runs   (    0.53 ms per token,  1892.86 tokens per second)
llama_print_timings: prompt eval time =     464.54 ms /    73 tokens (    6.36 ms per token,   157.15 tokens per second)
llama_print_timings:        eval time =     678.80 ms /     9 runs   (   75.42 ms per token,    13.26 tokens per second)
llama_print_timings:       total time =    1174.00 ms /    82 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.70 ms /    11 runs   (    0.52 ms per token,  1930.16 tokens per second)
llama_print_timings: prompt eval time =     467.13 ms /    73 tokens (    6.40 ms per token,   156.27 tokens per second)
llama_print_timings:        eval time =     742.93 ms /    10 runs   (   74.29 ms per token,    13.46 tokens per second)
llama_print_timings:       total time =    1244.15 ms /    83 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.21 ms /    10 runs   (    0.52 ms per token,  1919.39 tokens per second)
llama_print_timings: prompt eval time =     467.76 ms /    72 tokens (    6.50 ms per token,   153.93 tokens per second)
llama_print_timings:        eval time =     665.55 ms /     9 runs   (   73.95 ms per token,    13.52 tokens per second)
llama_print_timings:       total time =    1165.87 ms /    81 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.39 ms /    10 runs   (    0.54 ms per token,  1856.32 tokens per second)
llama_print_timings: prompt eval time =     469.85 ms /    73 tokens (    6.44 ms per token,   155.37 tokens per second)
llama_print_timings:        eval time =     662.60 ms /     9 runs   (   73.62 ms per token,    13.58 tokens per second)
llama_print_timings:       total time =    1167.34 ms /    82 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.29 ms /    10 runs   (    0.53 ms per token,  1892.15 tokens per second)
llama_print_timings: prompt eval time =     460.58 ms /    67 tokens (    6.87 ms per token,   145.47 tokens per second)
llama_print_timings:        eval time =     663.50 ms /     9 runs   (   73.72 ms per token,    13.56 tokens per second)
llama_print_timings:       total time =    1155.07 ms /    76 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       7.74 ms /    11 runs   (    0.70 ms per token,  1421.19 tokens per second)
llama_print_timings: prompt eval time =    1199.02 ms /   373 tokens (    3.21 ms per token,   311.09 tokens per second)
llama_print_timings:        eval time =     736.76 ms /    10 runs   (   73.68 ms per token,    13.57 tokens per second)
llama_print_timings:       total time =    2001.30 ms /   383 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.96 ms /    11 runs   (    0.54 ms per token,  1846.57 tokens per second)
llama_print_timings: prompt eval time =    2226.05 ms /   544 tokens (    4.09 ms per token,   244.38 tokens per second)
llama_print_timings:        eval time =     760.31 ms /    10 runs   (   76.03 ms per token,    13.15 tokens per second)
llama_print_timings:       total time =    3026.69 ms /   554 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.78 ms /    11 runs   (    0.53 ms per token,  1904.43 tokens per second)
llama_print_timings: prompt eval time =    1513.85 ms /   285 tokens (    5.31 ms per token,   188.26 tokens per second)
llama_print_timings:        eval time =     726.70 ms /    10 runs   (   72.67 ms per token,    13.76 tokens per second)
llama_print_timings:       total time =    2279.85 ms /   295 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       6.37 ms /    11 runs   (    0.58 ms per token,  1728.20 tokens per second)
llama_print_timings: prompt eval time =    1092.15 ms /   289 tokens (    3.78 ms per token,   264.62 tokens per second)
llama_print_timings:        eval time =     738.06 ms /    10 runs   (   73.81 ms per token,    13.55 tokens per second)
llama_print_timings:       total time =    1870.69 ms /   299 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       5.95 ms /    11 runs   (    0.54 ms per token,  1848.43 tokens per second)
llama_print_timings: prompt eval time =    1182.91 ms /   353 tokens (    3.35 ms per token,   298.42 tokens per second)
llama_print_timings:        eval time =     741.18 ms /    10 runs   (   74.12 ms per token,    13.49 tokens per second)
llama_print_timings:       total time =    1963.20 ms /   363 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       7.28 ms /    11 runs   (    0.66 ms per token,  1510.16 tokens per second)
llama_print_timings: prompt eval time =    1360.80 ms /   483 tokens (    2.82 ms per token,   354.94 tokens per second)
llama_print_timings:        eval time =     733.56 ms /    10 runs   (   73.36 ms per token,    13.63 tokens per second)
llama_print_timings:       total time =    2153.13 ms /   493 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =       7.77 ms /    11 runs   (    0.71 ms per token,  1415.88 tokens per second)
llama_print_timings: prompt eval time =    1088.04 ms /   306 tokens (    3.56 ms per token,   281.24 tokens per second)
llama_print_timings:        eval time =     716.06 ms /    10 runs   (   71.61 ms per token,    13.97 tokens per second)
llama_print_timings:       total time =    1866.41 ms /   316 tokens

In [ ]:
data_2['model_response'].head()

0    {"sentiment": "Positive" }
1    {"sentiment": "Positive" }
2    {"sentiment": "Positive" }
3    {"sentiment": "Positive" }
4    {"sentiment": "Positive" }
Name: model_response, dtype: object

In [ ]:
i = 3
print(data_2.loc[i, 'review_full'])

I have visited at jw lough/restourant. There were a first class service at lough, specially Ms.laxmi  who were superbed for handling the client need, me and my family lots enjoyed her specialty in the manner, and Laxmi is a very very good in the client service, I hope when I will come against I would definitely serve from Ms. Laxmi and she is wonderful girl in that service. See you again Ms. Laxmi for the your best service which I have received from you at jw lough/resourant. Thank you JW Marriott Hotel at Atrocity, Delhi

In [ ]:
print(data_2.loc[i, 'model_response'])

{"sentiment": "Positive" }

In [ ]:
# applying the function to the model response
data_2['model_response_parsed'] = data_2['model_response'].apply(extract_json_data)
data_2['model_response_parsed'].head()

0    {'sentiment': 'Positive'}
1    {'sentiment': 'Positive'}
2    {'sentiment': 'Positive'}
3    {'sentiment': 'Positive'}
4    {'sentiment': 'Positive'}
Name: model_response_parsed, dtype: object

In [ ]:
model_response_parsed_df_2 = pd.json_normalize(data_2['model_response_parsed'])
model_response_parsed_df_2.head()

  sentiment
0  Positive
1  Positive
2  Positive
3  Positive
4  Positive

In [ ]:
data_with_parsed_model_output_2 = pd.concat([data_2, model_response_parsed_df_2], axis=1)
data_with_parsed_model_output_2.head()

,restaurant_ID,rating_review,review_full,model_response,model_response_parsed,sentiment
0,FLV202,5,"Totally in love with the Auro of the place, re...","{""sentiment"": ""Positive"" }",{'sentiment': 'Positive'},Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,"{""sentiment"": ""Positive"" }",{'sentiment': 'Positive'},Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,"{""sentiment"": ""Positive"" }",{'sentiment': 'Positive'},Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,"{""sentiment"": ""Positive"" }",{'sentiment': 'Positive'},Positive
4,EAT456,5,Had a great experience in the restaurant food ...,"{""sentiment"": ""Positive"" }",{'sentiment': 'Positive'},Positive

In [ ]:
final_data_2 = data_with_parsed_model_output_2.drop(['model_response','model_response_parsed'], axis=1)
final_data_2.head()

,restaurant_ID,rating_review,review_full,sentiment
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,Positive
4,EAT456,5,Had a great experience in the restaurant food ...,Positive

In [ ]:
final_data_2['sentiment'].value_counts()

sentiment
Negative    7
Positive    6
neutral     5
Neutral     2
Name: count, dtype: int64

**Observations**

- The model successfully switches from phrases to a clean JSON format.

- It occasionally ignores the exact casing for labels like "Neutral" vs "neutral."

- It demonstrates that negative constraints like "Only return JSON" effectively reduce noise.

## 3. Identifying Overall Sentiment and Sentiment of Aspects of the Experience (Llama)

In [ ]:
# creating a copy of the data
data_3 = data.copy()

In [ ]:
# defining the instructions for the model
instruction_3 = """
    You are an AI analyzing restaurant reviews. Classify the overall sentiment of the provided review into the following categories:
    - "Positive"
    - "Negative"
    - "Neutral"

    Once that is done, check for a mention of the following aspects in the review and classify the sentiment of each aspect as "Positive", "Negative", or "Neutral":
    1. "Food Quality"
    2. "Service"
    3. "Ambience"

    Output the overall sentiment and sentiment for each category in a JSON format with the following keys:
    {
        "Overall": "your_sentiment_prediction",
        "Food Quality": "your_sentiment_prediction",
        "Service": "your_sentiment_prediction",
        "Ambience": "your_sentiment_prediction"
    }

    In case one of the three aspects is not mentioned in the review, set "Not Applicable" (including quotes) for the corresponding JSON key value.

    Only return the JSON, do not return any other information.
"""

In [ ]:
# Define specific parameters for Task 4
params_task_3 = {
    "max_tokens": 1024,
    "temperature": 0.01
}

# Updated Task 3 with JSON forcing
data_3['model_response'] = data_3['review_full'].apply(
    lambda x: "{" + generate_response(
        lcpp_llm,
        f"[INST]<<SYS>>\n{instruction_3}\n<</SYS>>\n{x}[/INST]\n{{",
        params_task_3
    )
)

Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      22.64 ms /    43 runs   (    0.53 ms per token,  1899.63 tokens per second)
llama_print_timings: prompt eval time =     629.63 ms /   175 tokens (    3.60 ms per token,   277.94 tokens per second)
llama_print_timings:        eval time =    3129.96 ms /    42 runs   (   74.52 ms per token,    13.42 tokens per second)
llama_print_timings:       total time =    3903.41 ms /   217 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      26.23 ms /    43 runs   (    0.61 ms per token,  1639.03 tokens per second)
llama_print_timings: prompt eval time =     683.74 ms /   245 tokens (    2.79 ms per token,   358.32 tokens per second)
llama_print_timings:        eval time =    3078.20 ms /    42 runs   (   73.29 ms per token,    13.64 tokens per second)
llama_print_timings:       total time =    3959.34 ms /   287 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      23.05 ms /    41 runs   (    0.56 ms per token,  1778.51 tokens per second)
llama_print_timings: prompt eval time =     396.51 ms /    35 tokens (   11.33 ms per token,    88.27 tokens per second)
llama_print_timings:        eval time =    2935.08 ms /    40 runs   (   73.38 ms per token,    13.63 tokens per second)
llama_print_timings:       total time =    3474.47 ms /    75 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      23.73 ms /    45 runs   (    0.53 ms per token,  1896.17 tokens per second)
llama_print_timings: prompt eval time =     605.80 ms /   146 tokens (    4.15 ms per token,   241.00 tokens per second)
llama_print_timings:        eval time =    3269.17 ms /    44 runs   (   74.30 ms per token,    13.46 tokens per second)
llama_print_timings:       total time =    4024.12 ms /   190 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      27.90 ms /    43 runs   (    0.65 ms per token,  1541.16 tokens per second)
llama_print_timings: prompt eval time =     650.38 ms /   183 tokens (    3.55 ms per token,   281.38 tokens per second)
llama_print_timings:        eval time =    3159.77 ms /    42 runs   (   75.23 ms per token,    13.29 tokens per second)
llama_print_timings:       total time =    4019.32 ms /   225 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      21.51 ms /    41 runs   (    0.52 ms per token,  1906.09 tokens per second)
llama_print_timings: prompt eval time =     675.02 ms /   225 tokens (    3.00 ms per token,   333.32 tokens per second)
llama_print_timings:        eval time =    3044.46 ms /    40 runs   (   76.11 ms per token,    13.14 tokens per second)
llama_print_timings:       total time =    3854.87 ms /   265 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      21.21 ms /    41 runs   (    0.52 ms per token,  1933.05 tokens per second)
llama_print_timings: prompt eval time =     675.36 ms /   231 tokens (    2.92 ms per token,   342.04 tokens per second)
llama_print_timings:        eval time =    3072.21 ms /    40 runs   (   76.81 ms per token,    13.02 tokens per second)
llama_print_timings:       total time =    3879.80 ms /   271 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      29.86 ms /    48 runs   (    0.62 ms per token,  1607.56 tokens per second)
llama_print_timings: prompt eval time =     462.98 ms /    72 tokens (    6.43 ms per token,   155.51 tokens per second)
llama_print_timings:        eval time =    3491.79 ms /    47 runs   (   74.29 ms per token,    13.46 tokens per second)
llama_print_timings:       total time =    4178.61 ms /   119 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      25.01 ms /    47 runs   (    0.53 ms per token,  1878.95 tokens per second)
llama_print_timings: prompt eval time =     469.50 ms /    73 tokens (    6.43 ms per token,   155.49 tokens per second)
llama_print_timings:        eval time =    3461.86 ms /    46 runs   (   75.26 ms per token,    13.29 tokens per second)
llama_print_timings:       total time =    4094.88 ms /   119 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      25.50 ms /    49 runs   (    0.52 ms per token,  1921.64 tokens per second)
llama_print_timings: prompt eval time =     469.93 ms /    73 tokens (    6.44 ms per token,   155.34 tokens per second)
llama_print_timings:        eval time =    3696.34 ms /    48 runs   (   77.01 ms per token,    12.99 tokens per second)
llama_print_timings:       total time =    4335.74 ms /   121 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      30.45 ms /    47 runs   (    0.65 ms per token,  1543.67 tokens per second)
llama_print_timings: prompt eval time =     469.93 ms /    72 tokens (    6.53 ms per token,   153.21 tokens per second)
llama_print_timings:        eval time =    3453.70 ms /    46 runs   (   75.08 ms per token,    13.32 tokens per second)
llama_print_timings:       total time =    4161.31 ms /   118 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      25.36 ms /    49 runs   (    0.52 ms per token,  1932.48 tokens per second)
llama_print_timings: prompt eval time =     471.04 ms /    73 tokens (    6.45 ms per token,   154.98 tokens per second)
llama_print_timings:        eval time =    3672.11 ms /    48 runs   (   76.50 ms per token,    13.07 tokens per second)
llama_print_timings:       total time =    4320.32 ms /   121 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      23.16 ms /    43 runs   (    0.54 ms per token,  1857.05 tokens per second)
llama_print_timings: prompt eval time =     466.62 ms /    67 tokens (    6.96 ms per token,   143.59 tokens per second)
llama_print_timings:        eval time =    3221.78 ms /    42 runs   (   76.71 ms per token,    13.04 tokens per second)
llama_print_timings:       total time =    3850.73 ms /   109 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      30.86 ms /    47 runs   (    0.66 ms per token,  1522.86 tokens per second)
llama_print_timings: prompt eval time =    1233.55 ms /   373 tokens (    3.31 ms per token,   302.38 tokens per second)
llama_print_timings:        eval time =    3468.76 ms /    46 runs   (   75.41 ms per token,    13.26 tokens per second)
llama_print_timings:       total time =    4950.22 ms /   419 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      24.76 ms /    46 runs   (    0.54 ms per token,  1857.84 tokens per second)
llama_print_timings: prompt eval time =    2295.51 ms /   544 tokens (    4.22 ms per token,   236.98 tokens per second)
llama_print_timings:        eval time =    3467.38 ms /    45 runs   (   77.05 ms per token,    12.98 tokens per second)
llama_print_timings:       total time =    5935.20 ms /   589 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      28.96 ms /    46 runs   (    0.63 ms per token,  1588.23 tokens per second)
llama_print_timings: prompt eval time =    1543.77 ms /   285 tokens (    5.42 ms per token,   184.61 tokens per second)
llama_print_timings:        eval time =    3397.75 ms /    45 runs   (   75.51 ms per token,    13.24 tokens per second)
llama_print_timings:       total time =    5160.88 ms /   330 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      24.75 ms /    47 runs   (    0.53 ms per token,  1898.91 tokens per second)
llama_print_timings: prompt eval time =    1111.68 ms /   289 tokens (    3.85 ms per token,   259.97 tokens per second)
llama_print_timings:        eval time =    3545.16 ms /    46 runs   (   77.07 ms per token,    12.98 tokens per second)
llama_print_timings:       total time =    4816.59 ms /   335 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      24.89 ms /    47 runs   (    0.53 ms per token,  1888.69 tokens per second)
llama_print_timings: prompt eval time =    1203.02 ms /   353 tokens (    3.41 ms per token,   293.43 tokens per second)
llama_print_timings:        eval time =    3559.82 ms /    46 runs   (   77.39 ms per token,    12.92 tokens per second)
llama_print_timings:       total time =    4924.52 ms /   399 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      27.30 ms /    46 runs   (    0.59 ms per token,  1685.23 tokens per second)
llama_print_timings: prompt eval time =    1409.03 ms /   483 tokens (    2.92 ms per token,   342.79 tokens per second)
llama_print_timings:        eval time =    3445.34 ms /    45 runs   (   76.56 ms per token,    13.06 tokens per second)
llama_print_timings:       total time =    5057.54 ms /   528 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      24.23 ms /    45 runs   (    0.54 ms per token,  1857.51 tokens per second)
llama_print_timings: prompt eval time =    1113.62 ms /   306 tokens (    3.64 ms per token,   274.78 tokens per second)
llama_print_timings:        eval time =    3379.16 ms /    44 runs   (   76.80 ms per token,    13.02 tokens per second)
llama_print_timings:       total time =    4645.97 ms /   350 tokens

In [ ]:
data_3['model_response'].head()

0    {"Overall": "Positive",\n"Food Quality": "Posi...
1    {"Overall": "Positive",\n"Food Quality": "Posi...
2    {"Overall": "Positive",\n"Food Quality": "Posi...
3    {"Overall": "Positive",\n"Food Quality": "Not ...
4    {"Overall": "Positive",\n"Food Quality": "Posi...
Name: model_response, dtype: object

In [ ]:
i = 2
print(data_3.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [ ]:
print(data_3.loc[i, 'model_response'])

{"Overall": "Positive",
"Food Quality": "Positive",
"Service": "Positive",
"Ambience": "Positive"
}

In [ ]:
# applying the function to the model response
data_3['model_response_parsed'] = data_3['model_response'].apply(extract_json_data)
data_3['model_response_parsed'].head()

0    {'Overall': 'Positive', 'Food Quality': 'Posit...
1    {'Overall': 'Positive', 'Food Quality': 'Posit...
2    {'Overall': 'Positive', 'Food Quality': 'Posit...
3    {'Overall': 'Positive', 'Food Quality': 'Not A...
4    {'Overall': 'Positive', 'Food Quality': 'Posit...
Name: model_response_parsed, dtype: object

In [ ]:
model_response_parsed_df_3 = pd.json_normalize(data_3['model_response_parsed'])
model_response_parsed_df_3.head()

    Overall    Food Quality         Service        Ambience
0  Positive        Positive  Not Applicable        Positive
1  Positive        Positive  Not Applicable        Positive
2  Positive        Positive        Positive        Positive
3  Positive  Not Applicable        Positive  Not Applicable
4  Positive        Positive        Positive  Not Applicable

In [ ]:
data_with_parsed_model_output_3 = pd.concat([data_3, model_response_parsed_df_3], axis=1)
data_with_parsed_model_output_3.head()

,restaurant_ID,rating_review,review_full,model_response,model_response_parsed,Overall,Food Quality,Service,Ambience
0,FLV202,5,"Totally in love with the Auro of the place, re...","{""Overall"": ""Positive"",\n""Food Quality"": ""Posi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Not Applicable,Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,"{""Overall"": ""Positive"",\n""Food Quality"": ""Posi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Not Applicable,Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,"{""Overall"": ""Positive"",\n""Food Quality"": ""Posi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,"{""Overall"": ""Positive"",\n""Food Quality"": ""Not ...","{'Overall': 'Positive', 'Food Quality': 'Not A...",Positive,Not Applicable,Positive,Not Applicable
4,EAT456,5,Had a great experience in the restaurant food ...,"{""Overall"": ""Positive"",\n""Food Quality"": ""Posi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Not Applicable

In [ ]:
final_data_3 = data_with_parsed_model_output_3.drop(['model_response','model_response_parsed'], axis=1)
final_data_3.head()

,restaurant_ID,rating_review,review_full,Overall,Food Quality,Service,Ambience
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive,Positive,Not Applicable,Positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,Positive,Positive,Not Applicable,Positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,Positive,Positive,Positive,Positive
3,TST101,5,I have visited at jw lough/restourant. There w...,Positive,Not Applicable,Positive,Not Applicable
4,EAT456,5,Had a great experience in the restaurant food ...,Positive,Positive,Positive,Not Applicable

In [ ]:
final_data_3['Overall'].value_counts()

Overall
Positive    7
Negative    7
Neutral     6
Name: count, dtype: int64

In [ ]:
final_data_3['Food Quality'].value_counts()

Food Quality
Positive          6
Not Applicable    5
Mixed             3
Neutral           3
Negative          2
Decent            1
Name: count, dtype: int64

In [ ]:
final_data_3['Service'].value_counts()

Service
Negative          8
Positive          7
Not Applicable    2
Slow              1
Inconsistent      1
Prompt            1
Name: count, dtype: int64

In [ ]:
final_data_3['Ambience'].value_counts()

Ambience
Not Applicable    11
Positive           7
Cozy               1
Casual             1
Name: count, dtype: int64

**Observations**

- The model accurately identifies the absence of specific topics using "Not Applicable."

- It maintains the requested JSON structure even when multiple keys are involved.

- It occasionally uses unauthorized labels like "Mixed" or "Decent" instead of the three provided.

## 3. Identifying Overall Sentiment and Sentiment of Aspects of the Experience (Mistral)

In [ ]:
# creating a copy of the data
data_3 = data.copy()

**Note:** We have already predicted the sentiment of the review. We can use this information while designing the prompt for this task. This way, it will reduce the computational complexity.

The sentiment is stored in the 'final_data_1' dataframe which is from the TASK 1.

In [ ]:
# defining the instructions for the model
instruction_3 = """
    You are provided a review and it's sentiment.

    Instructions:
    Classify the sentiment of each aspect as either of "Positive", "Negative", or "Neutral" only and not any other for the given review:
    1. "Food Quality"
    2. "Service"
    3. "Ambience"
    In case one of the three aspects is not mentioned in the review, return "Not Applicable" (including quotes) for the corresponding JSON key value.
    Return the output in the format {"Overall": given sentiment input,"Food Quality": "your_sentiment_prediction","Service": "your_sentiment_prediction","Ambience": "your_sentiment_prediction"}

    Only return the JSON, do not return any other information.

"""

In [ ]:
# 1. Define the parameters for Task 3 (Mistral)
params_task_3_mistral = {
    "max_tokens": 800,
    "temperature": 0.01
}

# 2. Apply the optimized function with JSON forcing
# We pass 'llm' (Mistral) and use the Q: / A: format
data_3['model_response'] = final_data_1.apply(
    lambda row: "{" + generate_response(
        llm,
        f"Q: {instruction_3}\nReview: {row['review_full']}\nSentiment: {row['sentiment']}\nA: {{",
        params_task_3_mistral
    ), axis=1
)

Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      24.00 ms /    44 runs   (    0.55 ms per token,  1833.03 tokens per second)
llama_print_timings: prompt eval time =    1952.78 ms /   353 tokens (    5.53 ms per token,   180.77 tokens per second)
llama_print_timings:        eval time =   12625.08 ms /    43 runs   (  293.61 ms per token,     3.41 tokens per second)
llama_print_timings:       total time =   14750.46 ms /   396 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      26.19 ms /    46 runs   (    0.57 ms per token,  1756.19 tokens per second)
llama_print_timings: prompt eval time =    1717.73 ms /   239 tokens (    7.19 ms per token,   139.14 tokens per second)
llama_print_timings:        eval time =   15021.25 ms /    45 runs   (  333.81 ms per token,     3.00 tokens per second)
llama_print_timings:       total time =   16986.69 ms /   284 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      24.85 ms /    44 runs   (    0.56 ms per token,  1770.34 tokens per second)
llama_print_timings: prompt eval time =     730.65 ms /    38 tokens (   19.23 ms per token,    52.01 tokens per second)
llama_print_timings:        eval time =   13005.12 ms /    43 runs   (  302.44 ms per token,     3.31 tokens per second)
llama_print_timings:       total time =   13919.11 ms /    81 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      26.64 ms /    48 runs   (    0.55 ms per token,  1802.07 tokens per second)
llama_print_timings: prompt eval time =     913.21 ms /   147 tokens (    6.21 ms per token,   160.97 tokens per second)
llama_print_timings:        eval time =   13780.90 ms /    47 runs   (  293.21 ms per token,     3.41 tokens per second)
llama_print_timings:       total time =   14893.68 ms /   194 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      25.61 ms /    46 runs   (    0.56 ms per token,  1796.17 tokens per second)
llama_print_timings: prompt eval time =     989.01 ms /   173 tokens (    5.72 ms per token,   174.92 tokens per second)
llama_print_timings:        eval time =   13203.93 ms /    45 runs   (  293.42 ms per token,     3.41 tokens per second)
llama_print_timings:       total time =   14382.03 ms /   218 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      25.22 ms /    44 runs   (    0.57 ms per token,  1744.51 tokens per second)
llama_print_timings: prompt eval time =    4969.20 ms /   221 tokens (   22.49 ms per token,    44.47 tokens per second)
llama_print_timings:        eval time =   12942.28 ms /    43 runs   (  300.98 ms per token,     3.32 tokens per second)
llama_print_timings:       total time =   18092.96 ms /   264 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      25.01 ms /    45 runs   (    0.56 ms per token,  1798.99 tokens per second)
llama_print_timings: prompt eval time =    5574.94 ms /   219 tokens (   25.46 ms per token,    39.28 tokens per second)
llama_print_timings:        eval time =   13128.16 ms /    44 runs   (  298.37 ms per token,     3.35 tokens per second)
llama_print_timings:       total time =   18889.40 ms /   263 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      27.42 ms /    48 runs   (    0.57 ms per token,  1750.61 tokens per second)
llama_print_timings: prompt eval time =     728.78 ms /    74 tokens (    9.85 ms per token,   101.54 tokens per second)
llama_print_timings:        eval time =   13906.69 ms /    47 runs   (  295.89 ms per token,     3.38 tokens per second)
llama_print_timings:       total time =   14834.22 ms /   121 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      25.39 ms /    46 runs   (    0.55 ms per token,  1811.88 tokens per second)
llama_print_timings: prompt eval time =     733.24 ms /    72 tokens (   10.18 ms per token,    98.19 tokens per second)
llama_print_timings:        eval time =   13247.23 ms /    45 runs   (  294.38 ms per token,     3.40 tokens per second)
llama_print_timings:       total time =   14168.86 ms /   117 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      27.18 ms /    48 runs   (    0.57 ms per token,  1766.00 tokens per second)
llama_print_timings: prompt eval time =     737.02 ms /    73 tokens (   10.10 ms per token,    99.05 tokens per second)
llama_print_timings:        eval time =   13718.38 ms /    47 runs   (  291.88 ms per token,     3.43 tokens per second)
llama_print_timings:       total time =   14649.34 ms /   120 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      25.86 ms /    46 runs   (    0.56 ms per token,  1779.08 tokens per second)
llama_print_timings: prompt eval time =     732.56 ms /    70 tokens (   10.47 ms per token,    95.55 tokens per second)
llama_print_timings:        eval time =   12985.30 ms /    45 runs   (  288.56 ms per token,     3.47 tokens per second)
llama_print_timings:       total time =   13899.88 ms /   115 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      26.22 ms /    46 runs   (    0.57 ms per token,  1754.19 tokens per second)
llama_print_timings: prompt eval time =     744.01 ms /    76 tokens (    9.79 ms per token,   102.15 tokens per second)
llama_print_timings:        eval time =   13135.31 ms /    45 runs   (  291.90 ms per token,     3.43 tokens per second)
llama_print_timings:       total time =   14071.97 ms /   121 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      25.46 ms /    45 runs   (    0.57 ms per token,  1767.83 tokens per second)
llama_print_timings: prompt eval time =     719.77 ms /    69 tokens (   10.43 ms per token,    95.86 tokens per second)
llama_print_timings:        eval time =   12738.29 ms /    44 runs   (  289.51 ms per token,     3.45 tokens per second)
llama_print_timings:       total time =   13636.15 ms /   113 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      27.25 ms /    47 runs   (    0.58 ms per token,  1724.71 tokens per second)
llama_print_timings: prompt eval time =    1977.12 ms /   358 tokens (    5.52 ms per token,   181.07 tokens per second)
llama_print_timings:        eval time =   13300.00 ms /    46 runs   (  289.13 ms per token,     3.46 tokens per second)
llama_print_timings:       total time =   15474.32 ms /   404 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      25.70 ms /    46 runs   (    0.56 ms per token,  1789.74 tokens per second)
llama_print_timings: prompt eval time =    3367.83 ms /   530 tokens (    6.35 ms per token,   157.37 tokens per second)
llama_print_timings:        eval time =   13310.32 ms /    45 runs   (  295.78 ms per token,     3.38 tokens per second)
llama_print_timings:       total time =   16931.59 ms /   575 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      26.12 ms /    47 runs   (    0.56 ms per token,  1799.18 tokens per second)
llama_print_timings: prompt eval time =    1791.57 ms /   278 tokens (    6.44 ms per token,   155.17 tokens per second)
llama_print_timings:        eval time =   13357.42 ms /    46 runs   (  290.38 ms per token,     3.44 tokens per second)
llama_print_timings:       total time =   15343.44 ms /   324 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      25.41 ms /    46 runs   (    0.55 ms per token,  1810.38 tokens per second)
llama_print_timings: prompt eval time =    1801.03 ms /   288 tokens (    6.25 ms per token,   159.91 tokens per second)
llama_print_timings:        eval time =   12967.41 ms /    45 runs   (  288.16 ms per token,     3.47 tokens per second)
llama_print_timings:       total time =   14958.86 ms /   333 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      26.46 ms /    46 runs   (    0.58 ms per token,  1738.34 tokens per second)
llama_print_timings: prompt eval time =    1969.01 ms /   339 tokens (    5.81 ms per token,   172.17 tokens per second)
llama_print_timings:        eval time =   13164.67 ms /    45 runs   (  292.55 ms per token,     3.42 tokens per second)
llama_print_timings:       total time =   15325.22 ms /   384 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      24.71 ms /    44 runs   (    0.56 ms per token,  1780.94 tokens per second)
llama_print_timings: prompt eval time =    2836.59 ms /   466 tokens (    6.09 ms per token,   164.28 tokens per second)
llama_print_timings:        eval time =   12680.27 ms /    43 runs   (  294.89 ms per token,     3.39 tokens per second)
llama_print_timings:       total time =   15709.74 ms /   509 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    2630.81 ms
llama_print_timings:      sample time =      26.32 ms /    46 runs   (    0.57 ms per token,  1747.99 tokens per second)
llama_print_timings: prompt eval time =    1905.00 ms /   301 tokens (    6.33 ms per token,   158.01 tokens per second)
llama_print_timings:        eval time =   14558.42 ms /    45 runs   (  323.52 ms per token,     3.09 tokens per second)
llama_print_timings:       total time =   16660.01 ms /   346 tokens

In [ ]:
data_3['model_response'].values

array(['{"Overall": "Positive",\n\t"Food Quality": "Positive",\n\t"Service": "Positive",\n\t"Ambience": "Positive"\n}',
       '{"Overall": "Positive",\n\t"Food Quality": "Positive",\n\t"Service": "Not Applicable",\n\t"Ambience": "Positive"\n}',
       '{"Overall": "Positive",\n\t"Food Quality": "Positive",\n\t"Service": "Positive",\n\t"Ambience": "Positive"\n}',
       '{"Overall": "Positive",\n\t"Food Quality": "Not Applicable",\n\t"Service": "Positive",\n\t"Ambience": "Not Applicable"\n}',
       '{"Overall": "Positive",\n\t"Food Quality": "Positive",\n\t"Service": "Positive",\n\t"Ambience": "Not Applicable"\n}',
       '{"Overall": "Positive",\n\t"Food Quality": "Positive",\n\t"Service": "Positive",\n\t"Ambience": "Positive"\n}',
       '{"Overall": "Positive",\n\t"Food Quality": "Neutral",\n\t"Service": "Positive",\n\t"Ambience": "Positive"\n}',
       '{"Overall": "Neutral",\n\t"Food Quality": "Neutral",\n\t"Service": "Negative",\n\t"Ambience": "Not Applicable"\n}',
       '{"Overall": "Neutral",\n\t"Food Quality": "Neutral",\n\t"Service": "Negative",\n\t"Ambience": "Positive"\n}',
       '{"Overall": "Neutral",\n\t"Food Quality": "Neutral",\n\t"Service": "Positive",\n\t"Ambience": "Not Applicable"\n}',
       '{"Overall": "Neutral",\n\t"Food Quality": "Decent",\n\t"Service": "Prompt",\n\t"Ambience": "Casual"\n}',
       '{"Overall": "Neutral",\n\t"Food Quality": "Neutral",\n\t"Service": "Negative",\n\t"Ambience": "Positive"\n}',
       '{"Overall": "Neutral",\n\t"Food Quality": "Negative",\n\t"Service": "Positive",\n\t"Ambience": "Positive"\n}',
       '{"Overall": "Negative",\n\t"Food Quality": "Not Applicable",\n\t"Service": "Negative",\n\t"Ambience": "Neutral"\n}',
       '{"Overall": "Negative",\n\t"Food Quality": "Negative",\n\t"Service": "Negative",\n\t"Ambience": "Not Applicable"\n}',
       '{"Overall": "Negative",\n\t"Food Quality": "Neutral",\n\t"Service": "Negative",\n\t"Ambience": "Not Applicable"\n}',
       '{"Overall": "Negative",\n\t"Food Quality": "Not Applicable",\n\t"Service": "Negative",\n\t"Ambience": "Negative"\n}',
       '{"Overall": "Negative",\n\t"Food Quality": "Not Applicable",\n\t"Service": "Negative",\n\t"Ambience": "Negative"\n}',
       '{"Overall": "Negative",\n\t"Food Quality": "Negative",\n\t"Service": "Negative",\n\t"Ambience": "Negative"\n}',
       '{"Overall": "Negative",\n\t"Food Quality": "Positive",\n\t"Service": "Negative",\n\t"Ambience": "Not Applicable"\n}'],
      dtype=object)

In [ ]:
i = 2
print(data_3.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [ ]:
print(data_3.loc[i, 'model_response'])

{"Overall": "Positive",
	"Food Quality": "Positive",
	"Service": "Positive",
	"Ambience": "Positive"
}

In [ ]:
# applying the function to the model response
data_3['model_response_parsed'] = data_3['model_response'].apply(extract_json_data)
data_3['model_response_parsed']

0     {'Overall': 'Positive', 'Food Quality': 'Posit...
1     {'Overall': 'Positive', 'Food Quality': 'Posit...
2     {'Overall': 'Positive', 'Food Quality': 'Posit...
3     {'Overall': 'Positive', 'Food Quality': 'Not A...
4     {'Overall': 'Positive', 'Food Quality': 'Posit...
5     {'Overall': 'Positive', 'Food Quality': 'Posit...
6     {'Overall': 'Positive', 'Food Quality': 'Neutr...
7     {'Overall': 'Neutral', 'Food Quality': 'Neutra...
8     {'Overall': 'Neutral', 'Food Quality': 'Neutra...
9     {'Overall': 'Neutral', 'Food Quality': 'Neutra...
10    {'Overall': 'Neutral', 'Food Quality': 'Decent...
11    {'Overall': 'Neutral', 'Food Quality': 'Neutra...
12    {'Overall': 'Neutral', 'Food Quality': 'Negati...
13    {'Overall': 'Negative', 'Food Quality': 'Not A...
14    {'Overall': 'Negative', 'Food Quality': 'Negat...
15    {'Overall': 'Negative', 'Food Quality': 'Neutr...
16    {'Overall': 'Negative', 'Food Quality': 'Not A...
17    {'Overall': 'Negative', 'Food Quality': 'Not A...
18    {'Overall': 'Negative', 'Food Quality': 'Negat...
19    {'Overall': 'Negative', 'Food Quality': 'Posit...
Name: model_response_parsed, dtype: object

In [ ]:
model_response_parsed_df_3 = pd.json_normalize(data_3['model_response_parsed'])
model_response_parsed_df_3

     Overall    Food Quality         Service        Ambience
0   Positive        Positive        Positive        Positive
1   Positive        Positive  Not Applicable        Positive
2   Positive        Positive        Positive        Positive
3   Positive  Not Applicable        Positive  Not Applicable
4   Positive        Positive        Positive  Not Applicable
5   Positive        Positive        Positive        Positive
6   Positive         Neutral        Positive        Positive
7    Neutral         Neutral        Negative  Not Applicable
8    Neutral         Neutral        Negative        Positive
9    Neutral         Neutral        Positive  Not Applicable
10   Neutral          Decent          Prompt          Casual
11   Neutral         Neutral        Negative        Positive
12   Neutral        Negative        Positive        Positive
13  Negative  Not Applicable        Negative         Neutral
14  Negative        Negative        Negative  Not Applicable
15  Negative         Neutral        Negative  Not Applicable
16  Negative  Not Applicable        Negative        Negative
17  Negative  Not Applicable        Negative        Negative
18  Negative        Negative        Negative        Negative
19  Negative        Positive        Negative  Not Applicable

In [ ]:
model_response_parsed_df_3 = model_response_parsed_df_3.apply(lambda x: x.astype(str).str.lower())

In [ ]:
data_with_parsed_model_output_3 = pd.concat([data_3, model_response_parsed_df_3], axis=1)
data_with_parsed_model_output_3.head()

,restaurant_ID,rating_review,review_full,model_response,model_response_parsed,Overall,Food Quality,Service,Ambience
0,FLV202,5,"Totally in love with the Auro of the place, re...","{""Overall"": ""Positive"",\n\t""Food Quality"": ""Po...","{'Overall': 'Positive', 'Food Quality': 'Posit...",positive,positive,positive,positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,"{""Overall"": ""Positive"",\n\t""Food Quality"": ""Po...","{'Overall': 'Positive', 'Food Quality': 'Posit...",positive,positive,not applicable,positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,"{""Overall"": ""Positive"",\n\t""Food Quality"": ""Po...","{'Overall': 'Positive', 'Food Quality': 'Posit...",positive,positive,positive,positive
3,TST101,5,I have visited at jw lough/restourant. There w...,"{""Overall"": ""Positive"",\n\t""Food Quality"": ""No...","{'Overall': 'Positive', 'Food Quality': 'Not A...",positive,not applicable,positive,not applicable
4,EAT456,5,Had a great experience in the restaurant food ...,"{""Overall"": ""Positive"",\n\t""Food Quality"": ""Po...","{'Overall': 'Positive', 'Food Quality': 'Posit...",positive,positive,positive,not applicable

In [ ]:
final_data_3 = data_with_parsed_model_output_3.drop(['model_response','model_response_parsed'], axis=1)
final_data_3.head()

,restaurant_ID,rating_review,review_full,Overall,Food Quality,Service,Ambience
0,FLV202,5,"Totally in love with the Auro of the place, re...",positive,positive,positive,positive
1,SAV303,5,Kailash colony is brimming with small cafes no...,positive,positive,not applicable,positive
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,positive,positive,positive,positive
3,TST101,5,I have visited at jw lough/restourant. There w...,positive,not applicable,positive,not applicable
4,EAT456,5,Had a great experience in the restaurant food ...,positive,positive,positive,not applicable

In [ ]:
final_data_3['Overall'].value_counts()

Overall
positive    7
negative    7
neutral     6
Name: count, dtype: int64

In [ ]:
final_data_3['Food Quality'].value_counts()

Food Quality
positive          6
neutral           6
not applicable    4
negative          3
decent            1
Name: count, dtype: int64

**Note:** One of the sentiment is 'if not exceptional'. This is most likely positive.

In [ ]:
final_data_3['Service'].value_counts()

Service
negative          10
positive           8
not applicable     1
prompt             1
Name: count, dtype: int64

In [ ]:
final_data_3['Ambience'].value_counts()

Ambience
positive          8
not applicable    7
negative          3
casual            1
neutral           1
Name: count, dtype: int64

**Observations**

- The model frequently introduces new, unapproved labels like "prompt" or "casual."

- It struggles with JSON syntax, sometimes including extra newline characters or tabs.

- It shows difficulty in distinguishing between "Neutral" and "Not Applicable" for missing aspects.

- These results highlight the performance constraints of the 7B Mistral model when compared to the higher-capacity 13B LLaMA model.

## 4. Identifying Overall Sentiment, Sentiment of Aspects of the Experience, and the Liked/Disliked Features of the Different Aspects of the Experience (Llama)

In [ ]:
# creating a copy of the data
data_4 = data.copy()

In [ ]:
# defining the instructions for the model
instruction_4 = """
    You are an AI tasked with analyzing restaurant reviews. Your goal is to classify the overall sentiment of the provided review into the following categories:
        - Positive
        - Negative
        - Neutral

    Subsequently, assess the sentiment of specific aspects mentioned in the review, namely:
        1. Food quality
        2. Service
        3. Ambience

    Further, identify liked and/or disliked features associated with each aspect in the review.

    Return the output in the specified JSON format, ensuring consistency and handling missing values appropriately:

    {
        "Overall": "your_sentiment_prediction",
        "Food Quality": "your_sentiment_prediction",
        "Service": "your_sentiment_prediction",
        "Ambience": "your_sentiment_prediction",
        "Food Quality Features": ["liked/disliked features"],
        "Service Features": ["liked/disliked features"],
        "Ambience Features": ["liked/disliked features"]
    }

    The sentiment prediction for Overall, Food Quality, Service, and Ambience should be one of "Positive", "Negative", or "Neutral" only.
    In case one of the three aspects is not mentioned in the review, set "Not Applicable" (including quotes) in the corresponding JSON key value for the sentiment.
    In case there are no liked/disliked features for a particular aspect, assign an empty list in the corresponding JSON key value for the aspect.

    Only return the JSON, do NOT return any other text or information.
"""

In [ ]:
# Define specific parameters for Task 4
params_task_4 = {
    "max_tokens": 1024,
    "temperature": 0.01
}

# Update the application
# Updated Task 4 with "Anchor Forcing"
data_4['model_response'] = data_4['review_full'].apply(
    lambda x: '{"Overall":' + generate_response(
        lcpp_llm,
        f"[INST]<<SYS>>\n{instruction_4}\n<</SYS>>\n{x}[/INST]\n{{\"Overall\":",
        params_task_4
    )
)

Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      57.17 ms /   102 runs   (    0.56 ms per token,  1784.18 tokens per second)
llama_print_timings: prompt eval time =    1864.08 ms /   560 tokens (    3.33 ms per token,   300.42 tokens per second)
llama_print_timings:        eval time =    7833.13 ms /   101 runs   (   77.56 ms per token,    12.89 tokens per second)
llama_print_timings:       total time =   10055.46 ms /   661 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      55.24 ms /    92 runs   (    0.60 ms per token,  1665.37 tokens per second)
llama_print_timings: prompt eval time =     745.58 ms /   248 tokens (    3.01 ms per token,   332.63 tokens per second)
llama_print_timings:        eval time =    7106.52 ms /    91 runs   (   78.09 ms per token,    12.81 tokens per second)
llama_print_timings:       total time =    8210.50 ms /   339 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      49.92 ms /    81 runs   (    0.62 ms per token,  1622.69 tokens per second)
llama_print_timings: prompt eval time =     424.68 ms /    38 tokens (   11.18 ms per token,    89.48 tokens per second)
llama_print_timings:        eval time =    6155.25 ms /    80 runs   (   76.94 ms per token,    13.00 tokens per second)
llama_print_timings:       total time =    6919.27 ms /   118 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      45.39 ms /    83 runs   (    0.55 ms per token,  1828.44 tokens per second)
llama_print_timings: prompt eval time =     645.86 ms /   149 tokens (    4.33 ms per token,   230.70 tokens per second)
llama_print_timings:        eval time =    6369.06 ms /    82 runs   (   77.67 ms per token,    12.87 tokens per second)
llama_print_timings:       total time =    7296.97 ms /   231 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      48.01 ms /    79 runs   (    0.61 ms per token,  1645.42 tokens per second)
llama_print_timings: prompt eval time =     663.26 ms /   186 tokens (    3.57 ms per token,   280.43 tokens per second)
llama_print_timings:        eval time =    5969.09 ms /    78 runs   (   76.53 ms per token,    13.07 tokens per second)
llama_print_timings:       total time =    6968.09 ms /   264 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      43.90 ms /    80 runs   (    0.55 ms per token,  1822.16 tokens per second)
llama_print_timings: prompt eval time =     685.79 ms /   228 tokens (    3.01 ms per token,   332.46 tokens per second)
llama_print_timings:        eval time =    5992.58 ms /    79 runs   (   75.86 ms per token,    13.18 tokens per second)
llama_print_timings:       total time =    6946.05 ms /   307 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      56.05 ms /    90 runs   (    0.62 ms per token,  1605.68 tokens per second)
llama_print_timings: prompt eval time =     680.93 ms /   234 tokens (    2.91 ms per token,   343.65 tokens per second)
llama_print_timings:        eval time =    6574.41 ms /    89 runs   (   73.87 ms per token,    13.54 tokens per second)
llama_print_timings:       total time =    7632.38 ms /   323 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      56.11 ms /    92 runs   (    0.61 ms per token,  1639.58 tokens per second)
llama_print_timings: prompt eval time =     461.75 ms /    75 tokens (    6.16 ms per token,   162.42 tokens per second)
llama_print_timings:        eval time =    6596.27 ms /    91 runs   (   72.49 ms per token,    13.80 tokens per second)
llama_print_timings:       total time =    7435.38 ms /   166 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      53.56 ms /    94 runs   (    0.57 ms per token,  1754.88 tokens per second)
llama_print_timings: prompt eval time =     456.33 ms /    76 tokens (    6.00 ms per token,   166.55 tokens per second)
llama_print_timings:        eval time =    6808.28 ms /    93 runs   (   73.21 ms per token,    13.66 tokens per second)
llama_print_timings:       total time =    7616.16 ms /   169 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      45.39 ms /    70 runs   (    0.65 ms per token,  1542.22 tokens per second)
llama_print_timings: prompt eval time =     467.63 ms /    76 tokens (    6.15 ms per token,   162.52 tokens per second)
llama_print_timings:        eval time =    5043.40 ms /    69 runs   (   73.09 ms per token,    13.68 tokens per second)
llama_print_timings:       total time =    5842.26 ms /   145 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      40.96 ms /    74 runs   (    0.55 ms per token,  1806.64 tokens per second)
llama_print_timings: prompt eval time =     464.19 ms /    75 tokens (    6.19 ms per token,   161.57 tokens per second)
llama_print_timings:        eval time =    5513.07 ms /    73 runs   (   75.52 ms per token,    13.24 tokens per second)
llama_print_timings:       total time =    6239.42 ms /   148 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      52.23 ms /    79 runs   (    0.66 ms per token,  1512.66 tokens per second)
llama_print_timings: prompt eval time =     469.63 ms /    76 tokens (    6.18 ms per token,   161.83 tokens per second)
llama_print_timings:        eval time =    5886.52 ms /    78 runs   (   75.47 ms per token,    13.25 tokens per second)
llama_print_timings:       total time =    6735.20 ms /   154 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      46.58 ms /    83 runs   (    0.56 ms per token,  1781.96 tokens per second)
llama_print_timings: prompt eval time =     475.51 ms /    70 tokens (    6.79 ms per token,   147.21 tokens per second)
llama_print_timings:        eval time =    6340.74 ms /    82 runs   (   77.33 ms per token,    12.93 tokens per second)
llama_print_timings:       total time =    7122.27 ms /   152 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      46.88 ms /    73 runs   (    0.64 ms per token,  1557.13 tokens per second)
llama_print_timings: prompt eval time =    1266.45 ms /   376 tokens (    3.37 ms per token,   296.89 tokens per second)
llama_print_timings:        eval time =    5481.60 ms /    72 runs   (   76.13 ms per token,    13.13 tokens per second)
llama_print_timings:       total time =    7102.31 ms /   448 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      65.64 ms /   108 runs   (    0.61 ms per token,  1645.36 tokens per second)
llama_print_timings: prompt eval time =    1900.43 ms /   547 tokens (    3.47 ms per token,   287.83 tokens per second)
llama_print_timings:        eval time =    8180.08 ms /   107 runs   (   76.45 ms per token,    13.08 tokens per second)
llama_print_timings:       total time =   10576.82 ms /   654 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      45.59 ms /    81 runs   (    0.56 ms per token,  1776.51 tokens per second)
llama_print_timings: prompt eval time =    1563.45 ms /   288 tokens (    5.43 ms per token,   184.21 tokens per second)
llama_print_timings:        eval time =    6172.21 ms /    80 runs   (   77.15 ms per token,    12.96 tokens per second)
llama_print_timings:       total time =    8030.42 ms /   368 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      45.70 ms /    73 runs   (    0.63 ms per token,  1597.23 tokens per second)
llama_print_timings: prompt eval time =    1129.48 ms /   292 tokens (    3.87 ms per token,   258.53 tokens per second)
llama_print_timings:        eval time =    5480.62 ms /    72 runs   (   76.12 ms per token,    13.14 tokens per second)
llama_print_timings:       total time =    6945.35 ms /   364 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      43.89 ms /    75 runs   (    0.59 ms per token,  1708.97 tokens per second)
llama_print_timings: prompt eval time =    1219.88 ms /   356 tokens (    3.43 ms per token,   291.83 tokens per second)
llama_print_timings:        eval time =    5694.26 ms /    74 runs   (   76.95 ms per token,    13.00 tokens per second)
llama_print_timings:       total time =    7214.92 ms /   430 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      57.34 ms /   101 runs   (    0.57 ms per token,  1761.48 tokens per second)
llama_print_timings: prompt eval time =    1416.42 ms /   486 tokens (    2.91 ms per token,   343.12 tokens per second)
llama_print_timings:        eval time =    7714.45 ms /   100 runs   (   77.14 ms per token,    12.96 tokens per second)
llama_print_timings:       total time =    9510.09 ms /   586 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =    1037.39 ms
llama_print_timings:      sample time =      60.23 ms /    99 runs   (    0.61 ms per token,  1643.64 tokens per second)
llama_print_timings: prompt eval time =    1136.33 ms /   309 tokens (    3.68 ms per token,   271.93 tokens per second)
llama_print_timings:        eval time =    7500.51 ms /    98 runs   (   76.54 ms per token,    13.07 tokens per second)
llama_print_timings:       total time =    9075.91 ms /   407 tokens

In [ ]:
i = 2
print(data_4.loc[i, 'review_full'])

Excellent taste and awesome decorum. Must visit. Subham Barnwal had given us a great service. One of the best experience.

In [ ]:
print(data_4.loc[i, 'model_response'])

{"Overall":"Positive",
"Food Quality": "Positive",
"Service": "Positive",
"Ambience": "Positive",
"Food Quality Features": ["Excellent taste"],
"Service Features": ["great service"],
"Ambience Features": ["awesome decorum"]}

In [ ]:
# applying the function to the model response
data_4['model_response_parsed'] = data_4['model_response'].apply(extract_json_data)
data_4['model_response_parsed'].head()

0    {'Overall': 'Positive', 'Food Quality': 'Posit...
1    {'Overall': 'Positive', 'Food Quality': 'Posit...
2    {'Overall': 'Positive', 'Food Quality': 'Posit...
3    {'Overall': 'Positive', 'Food Quality': 'Not A...
4    {'Overall': 'Positive', 'Food Quality': 'Posit...
Name: model_response_parsed, dtype: object

In [ ]:
data_4[data_4.model_response_parsed == {}]

Empty DataFrame
Columns: [restaurant_ID, rating_review, review_full, model_response, model_response_parsed]
Index: []

- There are three model responses that the JSON parser function could not parse
- We'll manually add the values for these three responses

In [ ]:
print(data_4.loc[3, 'model_response'])

{"Overall":"Positive",
"Food Quality": "Not Applicable",
"Service": "Positive",
"Ambience": "Not Applicable",
"Food Quality Features": [],
"Service Features": ["Ms. Laxmi's excellent client service"],
"Ambience Features": []}

In [ ]:
print(data_4.loc[6, 'model_response'])

{"Overall":"Positive",
"Food Quality": "Mixed",
"Service": "Positive",
"Ambience": "Positive",
"Food Quality Features": ["marinated with too much balsamic vinegar"],
"Service Features": [],
"Ambience Features": ["cozy feel", "soft lighting"]}

In [ ]:
print(data_4.loc[7, 'model_response'])

{"Overall":"Neutral",
"Food Quality": "Mixed",
"Service": "Neutral",
"Ambience": "Not Applicable",
"Food Quality Features": ["some dishes were tasty, others were just average"],
"Service Features": ["a few attentive staff members"],
"Ambience Features": []}

In [ ]:
upd_val_1 = {
    "Overall": "Positive",
    "Food Quality": "Positive",
    "Service": "Positive",
    "Ambience": "Not Applicable",
    "Food Quality Features": [],
    "Service Features": ["excellent service"],
    "Ambience Features": []
}

upd_val_2 = {
    "Overall": "Neutral",
    "Food Quality": "Neutral",
    "Service": "Neutral",
    "Ambience": "Not Applicable",
    "Food Quality Features": ["well prepared"],
    "Service Features": ["slow and inattentive"],
    "Ambience Features": ["interior is friendly", "not intimidating"]
}

upd_val_3 = {
    "Overall": "Neutral",
    "Food Quality": "Positive",
    "Service": "Negative",
    "Ambience": "Positive",
    "Food Quality Features": ["Some tasty, others average"],
    "Service Features": ["Attentive staff", "Slow service"],
    "Ambience Features": []
}

# defining the list of indices to update
idx_list = [3,6,7]
data_4.loc[idx_list, 'model_response_parsed'] = [upd_val_1, upd_val_2, upd_val_3]

**Note**: The values model responses that cannot be parsed correctly by the JSON parser function may vary with execution due to the randomness associated with LLMs. Kindly update as observed when run in your system.

In [ ]:
model_response_parsed_df_4 = pd.json_normalize(data_4['model_response_parsed'])
model_response_parsed_df_4.head()

,Overall,Food Quality,Service,Ambience,Food Quality Features,Service Features,Ambience Features
0,Positive,Positive,Positive,Positive,"[pizza straight from the oven, hummus and pita...",[disposable cutlery],"[quaint and cute, pure and positive]"
1,Positive,Positive,Not Applicable,Positive,"[exquisite taste, freshly made]",[],"[peaceful, plants enhanced its beauty]"
2,Positive,Positive,Positive,Positive,[Excellent taste],[great service],[awesome decorum]
3,Positive,Positive,Positive,Not Applicable,[],[excellent service],[]
4,Positive,Positive,Positive,Not Applicable,[fabulous],"[nice, professional]",[]

In [ ]:
data_with_parsed_model_output_4 = pd.concat([data_4, model_response_parsed_df_4], axis=1)
data_with_parsed_model_output_4.head()

,restaurant_ID,rating_review,review_full,model_response,model_response_parsed,Overall,Food Quality,Service,Ambience,Food Quality Features,Service Features,Ambience Features
0,FLV202,5,"Totally in love with the Auro of the place, re...","{""Overall"":""Positive"", \n""Food Quality"": ""Posi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive,"[pizza straight from the oven, hummus and pita...",[disposable cutlery],"[quaint and cute, pure and positive]"
1,SAV303,5,Kailash colony is brimming with small cafes no...,"{""Overall"":""Positive"", \n""Food Quality"": ""Posi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Not Applicable,Positive,"[exquisite taste, freshly made]",[],"[peaceful, plants enhanced its beauty]"
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,"{""Overall"":""Positive"", \n""Food Quality"": ""Posi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive,[Excellent taste],[great service],[awesome decorum]
3,TST101,5,I have visited at jw lough/restourant. There w...,"{""Overall"":""Positive"", \n""Food Quality"": ""Not ...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Not Applicable,[],[excellent service],[]
4,EAT456,5,Had a great experience in the restaurant food ...,"{""Overall"":""Positive"", \n""Food Quality"": ""Posi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Not Applicable,[fabulous],"[nice, professional]",[]

In [ ]:
final_data_4 = data_with_parsed_model_output_4.drop(['model_response','model_response_parsed'], axis=1)
final_data_4.head()

,restaurant_ID,rating_review,review_full,Overall,Food Quality,Service,Ambience,Food Quality Features,Service Features,Ambience Features
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive,Positive,Positive,Positive,"[pizza straight from the oven, hummus and pita...",[disposable cutlery],"[quaint and cute, pure and positive]"
1,SAV303,5,Kailash colony is brimming with small cafes no...,Positive,Positive,Not Applicable,Positive,"[exquisite taste, freshly made]",[],"[peaceful, plants enhanced its beauty]"
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,Positive,Positive,Positive,Positive,[Excellent taste],[great service],[awesome decorum]
3,TST101,5,I have visited at jw lough/restourant. There w...,Positive,Positive,Positive,Not Applicable,[],[excellent service],[]
4,EAT456,5,Had a great experience in the restaurant food ...,Positive,Positive,Positive,Not Applicable,[fabulous],"[nice, professional]",[]

In [ ]:
final_data_4['Overall'].value_counts()

Overall
Neutral     7
Negative    7
Positive    6
Name: count, dtype: int64

In [ ]:
final_data_4['Food Quality'].value_counts()

Food Quality
Positive          9
Not Applicable    4
Neutral           3
Mixed             2
Negative          2
Name: count, dtype: int64

In [ ]:
final_data_4['Service'].value_counts()

Service
Positive          8
Negative          7
Not Applicable    2
Neutral           2
Inconsistent      1
Name: count, dtype: int64

In [ ]:
final_data_4['Ambience'].value_counts()

Ambience
Not Applicable    11
Positive           7
Cozy               1
Neutral            1
Name: count, dtype: int64

**Observations**

- The model successfully extracts specific text snippets as "Features" for each category.

- It correctly uses empty lists [] when no specific features are mentioned in the text.

- It maintains high accuracy while performing classification and extraction in a single pass.

## 5. Identifying Overall Sentiment, Sentiment of Aspects of the Experience, Liked/Disliked Features of the Different Aspects of the Experience, and Sharing a Response (Llama)

In [ ]:
# creating a copy of the data
data_5 = data.copy()

In [ ]:
instruction_5 = """
You are a sentiment analysis system for restaurant reviews.

Your tasks:

Step 1: Classify the overall sentiment of the review as exactly one of:
"Positive"
"Negative"
"Neutral"

Step 2: For each of the following aspects, determine:
1. Whether the aspect is mentioned
2. If mentioned, classify its sentiment as exactly one of:
   "Positive"
   "Negative"
   "Neutral"
3. If NOT mentioned, return:
   "Not Applicable"

Aspects:
- Food Quality
- Service
- Ambience

Step 3: Extract specific liked or disliked features for each mentioned aspect.
- Return short phrases only.
- Do not generate new information.
- If no features are mentioned for an aspect, return an empty list [].
- If the aspect is "Not Applicable", return an empty list [] for its features.

Step 4: Generate a professional and empathetic customer response:
- Always begin with a thank you.
- If Overall = "Positive" → express appreciation and invite them again.
- If Overall = "Neutral" → thank them and ask how the experience could be improved.
- If Overall = "Negative" → apologize sincerely and mention that the concerns will be addressed.

OUTPUT FORMAT RULES (STRICT):
- Return ONLY valid JSON.
- Do NOT include any explanation or extra text.
- Do NOT include trailing commas.
- All sentiment values must be strings and single valued.
- All feature values must be lists of strings.
- Use double quotes for all keys and string values.
- Ensure valid JSON syntax.

Return output in exactly this structure:

{
    "Overall": "Positive/Negative/Neutral",
    "Food Quality": "Positive/Negative/Neutral/Not Applicable",
    "Service": "Positive/Negative/Neutral/Not Applicable",
    "Ambience": "Positive/Negative/Neutral/Not Applicable",
    "Response": "Full customer response text",
    "Food Quality Features": ["feature1", "feature2"],
    "Service Features": ["feature1", "feature2"],
    "Ambience Features": ["feature1", "feature2"]
}
"""

In [ ]:
# Define parameters for Task 5
params_task_5 = {
    "max_tokens": 1440,
    "temperature": 0,
    "top_p": 1,
}

# Update the application
# Updated Task 5 with "Anchor Forcing"
data_5['model_response'] = data_5['review_full'].apply(
    lambda x: '{"Overall":' + generate_response(
        lcpp_llm,
        f"[INST]<<SYS>>\n{instruction_5}\n<</SYS>>\n{x}[/INST]\n{{\"Overall\":",
        params_task_5
    )
)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      77.55 ms /   147 runs   (    0.53 ms per token,  1895.45 tokens per second)
llama_print_timings: prompt eval time =    2037.39 ms /   751 tokens (    2.71 ms per token,   368.61 tokens per second)
llama_print_timings:        eval time =   11167.86 ms /   146 runs   (   76.49 ms per token,    13.07 tokens per second)
llama_print_timings:       total time =   13799.21 ms /   897 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      86.27 ms /   159 runs   (    0.54 ms per token,  1843.07 tokens per second)
llama_print_timings: prompt eval time =     726.85 ms /   248 tokens (    2.93 ms per token,   341.20 tokens per second)
llama_print_timings:        eval time =   12667.70 ms /   158 runs   (   80.18 ms per token,    12.47 tokens per second)
llama_print_timings:       total time =   14064.73 ms /   406 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      78.96 ms /   141 runs   (    0.56 ms per token,  1785.62 tokens per second)
llama_print_timings: prompt eval time =     444.21 ms /    38 tokens (   11.69 ms per token,    85.55 tokens per second)
llama_print_timings:        eval time =   11883.54 ms /   140 runs   (   84.88 ms per token,    11.78 tokens per second)
llama_print_timings:       total time =   12912.67 ms /   178 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      43.01 ms /    87 runs   (    0.49 ms per token,  2022.69 tokens per second)
llama_print_timings: prompt eval time =     695.16 ms /   149 tokens (    4.67 ms per token,   214.34 tokens per second)
llama_print_timings:        eval time =    7296.82 ms /    86 runs   (   84.85 ms per token,    11.79 tokens per second)
llama_print_timings:       total time =    8305.46 ms /   235 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      81.16 ms /   155 runs   (    0.52 ms per token,  1909.93 tokens per second)
llama_print_timings: prompt eval time =     715.31 ms /   186 tokens (    3.85 ms per token,   260.03 tokens per second)
llama_print_timings:        eval time =   12005.26 ms /   154 runs   (   77.96 ms per token,    12.83 tokens per second)
llama_print_timings:       total time =   13345.58 ms /   340 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      96.18 ms /   178 runs   (    0.54 ms per token,  1850.66 tokens per second)
llama_print_timings: prompt eval time =     711.55 ms /   228 tokens (    3.12 ms per token,   320.43 tokens per second)
llama_print_timings:        eval time =   13583.48 ms /   177 runs   (   76.74 ms per token,    13.03 tokens per second)
llama_print_timings:       total time =   15058.29 ms /   405 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      95.36 ms /   181 runs   (    0.53 ms per token,  1897.99 tokens per second)
llama_print_timings: prompt eval time =     704.98 ms /   234 tokens (    3.01 ms per token,   331.93 tokens per second)
llama_print_timings:        eval time =   13877.25 ms /   180 runs   (   77.10 ms per token,    12.97 tokens per second)
llama_print_timings:       total time =   15324.14 ms /   414 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      73.86 ms /   140 runs   (    0.53 ms per token,  1895.35 tokens per second)
llama_print_timings: prompt eval time =     489.10 ms /    75 tokens (    6.52 ms per token,   153.34 tokens per second)
llama_print_timings:        eval time =   10725.69 ms /   139 runs   (   77.16 ms per token,    12.96 tokens per second)
llama_print_timings:       total time =   11778.93 ms /   214 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      83.43 ms /   158 runs   (    0.53 ms per token,  1893.85 tokens per second)
llama_print_timings: prompt eval time =     501.69 ms /    76 tokens (    6.60 ms per token,   151.49 tokens per second)
llama_print_timings:        eval time =   12445.03 ms /   157 runs   (   79.27 ms per token,    12.62 tokens per second)
llama_print_timings:       total time =   13590.52 ms /   233 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      70.14 ms /   133 runs   (    0.53 ms per token,  1896.32 tokens per second)
llama_print_timings: prompt eval time =     505.93 ms /    76 tokens (    6.66 ms per token,   150.22 tokens per second)
llama_print_timings:        eval time =   10406.06 ms /   132 runs   (   78.83 ms per token,    12.68 tokens per second)
llama_print_timings:       total time =   11450.21 ms /   208 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      77.38 ms /   146 runs   (    0.53 ms per token,  1886.89 tokens per second)
llama_print_timings: prompt eval time =     506.13 ms /    75 tokens (    6.75 ms per token,   148.18 tokens per second)
llama_print_timings:        eval time =   11206.52 ms /   145 runs   (   77.29 ms per token,    12.94 tokens per second)
llama_print_timings:       total time =   12300.55 ms /   220 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      77.70 ms /   146 runs   (    0.53 ms per token,  1879.14 tokens per second)
llama_print_timings: prompt eval time =     491.64 ms /    76 tokens (    6.47 ms per token,   154.58 tokens per second)
llama_print_timings:        eval time =   11191.51 ms /   145 runs   (   77.18 ms per token,    12.96 tokens per second)
llama_print_timings:       total time =   12270.65 ms /   221 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      80.43 ms /   154 runs   (    0.52 ms per token,  1914.71 tokens per second)
llama_print_timings: prompt eval time =     485.30 ms /    70 tokens (    6.93 ms per token,   144.24 tokens per second)
llama_print_timings:        eval time =   11793.72 ms /   153 runs   (   77.08 ms per token,    12.97 tokens per second)
llama_print_timings:       total time =   12891.43 ms /   223 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      94.74 ms /   179 runs   (    0.53 ms per token,  1889.44 tokens per second)
llama_print_timings: prompt eval time =    1294.11 ms /   376 tokens (    3.44 ms per token,   290.55 tokens per second)
llama_print_timings:        eval time =   13991.45 ms /   178 runs   (   78.60 ms per token,    12.72 tokens per second)
llama_print_timings:       total time =   15997.28 ms /   554 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      95.05 ms /   183 runs   (    0.52 ms per token,  1925.22 tokens per second)
llama_print_timings: prompt eval time =    1965.17 ms /   547 tokens (    3.59 ms per token,   278.35 tokens per second)
llama_print_timings:        eval time =   14613.64 ms /   182 runs   (   80.29 ms per token,    12.45 tokens per second)
llama_print_timings:       total time =   17317.07 ms /   729 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      49.95 ms /    97 runs   (    0.51 ms per token,  1941.94 tokens per second)
llama_print_timings: prompt eval time =    1611.71 ms /   288 tokens (    5.60 ms per token,   178.69 tokens per second)
llama_print_timings:        eval time =    7436.53 ms /    96 runs   (   77.46 ms per token,    12.91 tokens per second)
llama_print_timings:       total time =    9427.52 ms /   384 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =     103.36 ms /   192 runs   (    0.54 ms per token,  1857.62 tokens per second)
llama_print_timings: prompt eval time =    1190.98 ms /   292 tokens (    4.08 ms per token,   245.18 tokens per second)
llama_print_timings:        eval time =   14858.34 ms /   191 runs   (   77.79 ms per token,    12.85 tokens per second)
llama_print_timings:       total time =   16844.79 ms /   483 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =     101.42 ms /   193 runs   (    0.53 ms per token,  1902.88 tokens per second)
llama_print_timings: prompt eval time =    1268.15 ms /   356 tokens (    3.56 ms per token,   280.72 tokens per second)
llama_print_timings:        eval time =   15171.81 ms /   192 runs   (   79.02 ms per token,    12.66 tokens per second)
llama_print_timings:       total time =   17221.84 ms /   548 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      94.64 ms /   183 runs   (    0.52 ms per token,  1933.62 tokens per second)
llama_print_timings: prompt eval time =    1492.88 ms /   486 tokens (    3.07 ms per token,   325.55 tokens per second)
llama_print_timings:        eval time =   14663.34 ms /   182 runs   (   80.57 ms per token,    12.41 tokens per second)
llama_print_timings:       total time =   16888.40 ms /   668 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     717.01 ms
llama_print_timings:      sample time =      89.76 ms /   170 runs   (    0.53 ms per token,  1893.90 tokens per second)
llama_print_timings: prompt eval time =    1208.48 ms /   309 tokens (    3.91 ms per token,   255.69 tokens per second)
llama_print_timings:        eval time =   13247.10 ms /   169 runs   (   78.39 ms per token,    12.76 tokens per second)
llama_print_timings:       total time =   15141.08 ms /   478 tokens

In [ ]:
i = 3
print(data_5.loc[i, 'review_full'])

I have visited at jw lough/restourant. There were a first class service at lough, specially Ms.laxmi  who were superbed for handling the client need, me and my family lots enjoyed her specialty in the manner, and Laxmi is a very very good in the client service, I hope when I will come against I would definitely serve from Ms. Laxmi and she is wonderful girl in that service. See you again Ms. Laxmi for the your best service which I have received from you at jw lough/resourant. Thank you JW Marriott Hotel at Atrocity, Delhi

In [ ]:
print(data_5.loc[i, 'model_response'])

{"Overall":"Positive", "Food Quality": "Not Applicable", "Service": "Positive", "Ambience": "Not Applicable", "Response": "Thank you JW Marriott Hotel at Atrocity, Delhi", "Food Quality Features": [], "Service Features": ["superbed for handling the client need"], "Ambience Features": []}

In [ ]:
# applying the function to the model response
data_5['model_response_parsed'] = data_5['model_response'].apply(extract_json_data)
data_5['model_response_parsed'].head()

0    {'Overall': 'Positive', 'Food Quality': 'Posit...
1    {'Overall': 'Positive', 'Food Quality': 'Posit...
2    {'Overall': 'Positive', 'Food Quality': 'Posit...
3    {'Overall': 'Positive', 'Food Quality': 'Not A...
4    {'Overall': 'Positive', 'Food Quality': 'Posit...
Name: model_response_parsed, dtype: object

In [ ]:
model_response_parsed_df_5 = pd.json_normalize(data_5['model_response_parsed'])
model_response_parsed_df_5.head()

,Overall,Food Quality,Service,Ambience,Response,Food Quality Features,Service Features,Ambience Features
0,Positive,Positive,Positive,Positive,Thank you so much for your kind words! We're t...,"[pizza, hummus]",[open kitchen],"[quaint, cute]"
1,Positive,Positive,Not Applicable,Positive,Thank you for your kind words! We're thrilled ...,"[freshly made, Wood Fired oven, exquisite taste]",[],"[peaceful, plants]"
2,Positive,Positive,Positive,Positive,Thank you so much for your kind words! We're t...,[excellent taste],[great service],[awesome decorum]
3,Positive,Not Applicable,Positive,Not Applicable,"Thank you JW Marriott Hotel at Atrocity, Delhi",[],[superbed for handling the client need],[]
4,Positive,Positive,Positive,Not Applicable,Thank you so much for taking the time to share...,[fabulous],"[professional, helpful]",[]

In [ ]:
data_with_parsed_model_output_5 = pd.concat([data_5, model_response_parsed_df_5], axis=1)
data_with_parsed_model_output_5.head()

,restaurant_ID,rating_review,review_full,model_response,model_response_parsed,Overall,Food Quality,Service,Ambience,Response,Food Quality Features,Service Features,Ambience Features
0,FLV202,5,"Totally in love with the Auro of the place, re...","{""Overall"":""Positive"", ""Food Quality"": ""Positi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive,Thank you so much for your kind words! We're t...,"[pizza, hummus]",[open kitchen],"[quaint, cute]"
1,SAV303,5,Kailash colony is brimming with small cafes no...,"{""Overall"":""Positive"",\n""Food Quality"": ""Posit...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Not Applicable,Positive,Thank you for your kind words! We're thrilled ...,"[freshly made, Wood Fired oven, exquisite taste]",[],"[peaceful, plants]"
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,"{""Overall"":""Positive"",\n""Food Quality"": ""Posit...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Positive,Thank you so much for your kind words! We're t...,[excellent taste],[great service],[awesome decorum]
3,TST101,5,I have visited at jw lough/restourant. There w...,"{""Overall"":""Positive"", ""Food Quality"": ""Not Ap...","{'Overall': 'Positive', 'Food Quality': 'Not A...",Positive,Not Applicable,Positive,Not Applicable,"Thank you JW Marriott Hotel at Atrocity, Delhi",[],[superbed for handling the client need],[]
4,EAT456,5,Had a great experience in the restaurant food ...,"{""Overall"":""Positive"", ""Food Quality"": ""Positi...","{'Overall': 'Positive', 'Food Quality': 'Posit...",Positive,Positive,Positive,Not Applicable,Thank you so much for taking the time to share...,[fabulous],"[professional, helpful]",[]

In [ ]:
final_data_5 = data_with_parsed_model_output_5.drop(['model_response','model_response_parsed'], axis=1)
final_data_5.head()

,restaurant_ID,rating_review,review_full,Overall,Food Quality,Service,Ambience,Response,Food Quality Features,Service Features,Ambience Features
0,FLV202,5,"Totally in love with the Auro of the place, re...",Positive,Positive,Positive,Positive,Thank you so much for your kind words! We're t...,"[pizza, hummus]",[open kitchen],"[quaint, cute]"
1,SAV303,5,Kailash colony is brimming with small cafes no...,Positive,Positive,Not Applicable,Positive,Thank you for your kind words! We're thrilled ...,"[freshly made, Wood Fired oven, exquisite taste]",[],"[peaceful, plants]"
2,YUM789,5,Excellent taste and awesome decorum. Must visi...,Positive,Positive,Positive,Positive,Thank you so much for your kind words! We're t...,[excellent taste],[great service],[awesome decorum]
3,TST101,5,I have visited at jw lough/restourant. There w...,Positive,Not Applicable,Positive,Not Applicable,"Thank you JW Marriott Hotel at Atrocity, Delhi",[],[superbed for handling the client need],[]
4,EAT456,5,Had a great experience in the restaurant food ...,Positive,Positive,Positive,Not Applicable,Thank you so much for taking the time to share...,[fabulous],"[professional, helpful]",[]

In [ ]:
final_data_5['Overall'].value_counts()

Overall
Neutral     7
Negative    7
Positive    6
Name: count, dtype: int64

In [ ]:
final_data_5['Food Quality'].value_counts()

Food Quality
Positive                 9
Mixed                    4
Not Applicable           3
Negative                 3
Decent/Not Applicable    1
Name: count, dtype: int64

In [ ]:
final_data_5['Service'].value_counts()

Service
Positive                 6
Negative                 6
Not Applicable           3
Good                     2
Slow                     1
Inconsistent             1
Prompt/Not Applicable    1
Name: count, dtype: int64

In [ ]:
final_data_5['Ambience'].value_counts()

Ambience
Not Applicable           11
Positive                  5
Good                      2
Cozy                      1
Casual/Not Applicable     1
Name: count, dtype: int64

**Observations**

- The step-by-step instruction format ensures the final response matches the detected sentiment.

- It strictly follows the response generation rules.

- It eliminates all conversational filler, returning only the final structured JSON object.

- But we still see extra lables in aspect based sentiments. Reason being while llama is a 13 billion parameter model, we still need bigger models to do a lot of complex combination of tasks in single pass.

<font size=6 color="navyblue">Power Ahead!</font>
___